/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Administrador.AdmFuncionario;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import objetos.Funcionario;
import objetos_dao.FuncionarioDAO;

/**
 *
 * @author GabrielFelipe
 */
public class EditFuncAlerta extends javax.swing.JFrame {

   FuncionarioDAO funcionarioBanco = new FuncionarioDAO();
   Funcionario funcionario_novo;
   Funcionario funcionario_antigo;
   
   OpFuncionarios opf;

    public EditFuncAlerta(Funcionario antigo, Funcionario novo, OpFuncionarios opf) {
        funcionario_antigo = antigo;
        funcionario_novo = novo;
        this.opf = opf;
        
        initComponents();
    }

    //EditFuncAlerta(Funcionario get, Funcionario tempFunc) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        NomeEditFunc1 = new javax.swing.JLabel();
        nomeEditFunc1 = new javax.swing.JLabel();
        CPFEditFunc1 = new javax.swing.JLabel();
        cpfEditFunc1 = new javax.swing.JLabel();
        EspecialidadeEditFunc1 = new javax.swing.JLabel();
        especialidadeEditFunc1 = new javax.swing.JLabel();
        SalarioEditFunc1 = new javax.swing.JLabel();
        salarioEditFunc1 = new javax.swing.JLabel();
        TelefoneEditFunc1 = new javax.swing.JLabel();
        telefoneEditFunc1 = new javax.swing.JLabel();
        EmailEditFunc1 = new javax.swing.JLabel();
        emailEditFunc1 = new javax.swing.JLabel();
        SetaEditFunc = new javax.swing.JLabel();
        NomeEditFunc2 = new javax.swing.JLabel();
        nomeEditFunc2 = new javax.swing.JLabel();
        CPFEditFunc2 = new javax.swing.JLabel();
        cpfEditFunc2 = new javax.swing.JLabel();
        EspecialidadeEditFunc2 = new javax.swing.JLabel();
        especialidadeEditFunc2 = new javax.swing.JLabel();
        SalarioEditFunc2 = new javax.swing.JLabel();
        salarioEditFunc2 = new javax.swing.JLabel();
        TelefoneEditFunc2 = new javax.swing.JLabel();
        telefoneEditFunc2 = new javax.swing.JLabel();
        EmaiEditFunc2 = new javax.swing.JLabel();
        emailEditFunc2 = new javax.swing.JLabel();
        ConfirmaEditFunc = new javax.swing.JButton();
        CancelaEditFunc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Editar o Funcionário: ");
        Titulo.setToolTipText("");

        NomeEditFunc1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeEditFunc1.setText("Nome:");
        NomeEditFunc1.setToolTipText("");

        nomeEditFunc1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeEditFunc1.setText("???");

        CPFEditFunc1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CPFEditFunc1.setText("CPF:");
        CPFEditFunc1.setToolTipText("");

        cpfEditFunc1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cpfEditFunc1.setText("???");

        EspecialidadeEditFunc1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        EspecialidadeEditFunc1.setText("Esp.:");
        EspecialidadeEditFunc1.setToolTipText("");

        especialidadeEditFunc1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        especialidadeEditFunc1.setText("???");

        SalarioEditFunc1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        SalarioEditFunc1.setText("Salário:");
        SalarioEditFunc1.setToolTipText("");

        salarioEditFunc1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        salarioEditFunc1.setText("???");

        TelefoneEditFunc1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        TelefoneEditFunc1.setText("Telefone:");
        TelefoneEditFunc1.setToolTipText("");

        telefoneEditFunc1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        telefoneEditFunc1.setText("???");

        EmailEditFunc1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        EmailEditFunc1.setText("Email:");
        EmailEditFunc1.setToolTipText("");

        emailEditFunc1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        emailEditFunc1.setText("???");

        SetaEditFunc.setFont(new java.awt.Font("Dialog", 1, 55)); // NOI18N
        SetaEditFunc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SetaEditFunc.setText("→");

        NomeEditFunc2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeEditFunc2.setText("Nome:");
        NomeEditFunc2.setToolTipText("");

        nomeEditFunc2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeEditFunc2.setText("???");

        CPFEditFunc2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CPFEditFunc2.setText("CPF:");
        CPFEditFunc2.setToolTipText("");

        cpfEditFunc2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cpfEditFunc2.setText("???");

        EspecialidadeEditFunc2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        EspecialidadeEditFunc2.setText("Esp.:");
        EspecialidadeEditFunc2.setToolTipText("");

        especialidadeEditFunc2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        especialidadeEditFunc2.setText("???");

        SalarioEditFunc2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        SalarioEditFunc2.setText("Salário:");
        SalarioEditFunc2.setToolTipText("");

        salarioEditFunc2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        salarioEditFunc2.setText("???");

        TelefoneEditFunc2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        TelefoneEditFunc2.setText("Telefone:");
        TelefoneEditFunc2.setToolTipText("");

        telefoneEditFunc2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        telefoneEditFunc2.setText("???");

        EmaiEditFunc2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        EmaiEditFunc2.setText("Email:");
        EmaiEditFunc2.setToolTipText("");

        emailEditFunc2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        emailEditFunc2.setText("???");

        ConfirmaEditFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ConfirmaEditFunc.setText("Sim");
        ConfirmaEditFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmaEditFuncActionPerformed(evt);
            }
        });

        CancelaEditFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CancelaEditFunc.setText("Cancelar");
        CancelaEditFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelaEditFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(NomeEditFunc1)
                        .addGap(12, 12, 12)
                        .addComponent(nomeEditFunc1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(EmailEditFunc1)
                        .addGap(12, 12, 12)
                        .addComponent(emailEditFunc1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TelefoneEditFunc1)
                        .addGap(12, 12, 12)
                        .addComponent(telefoneEditFunc1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(CPFEditFunc1)
                                .addGap(12, 12, 12)
                                .addComponent(cpfEditFunc1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(SalarioEditFunc1)
                                .addGap(12, 12, 12)
                                .addComponent(salarioEditFunc1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(EspecialidadeEditFunc1)
                                .addGap(12, 12, 12)
                                .addComponent(especialidadeEditFunc1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SetaEditFunc)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(NomeEditFunc2)
                        .addGap(12, 12, 12)
                        .addComponent(nomeEditFunc2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(CPFEditFunc2)
                        .addGap(12, 12, 12)
                        .addComponent(cpfEditFunc2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TelefoneEditFunc2)
                                .addGap(12, 12, 12)
                                .addComponent(telefoneEditFunc2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(EmaiEditFunc2)
                                .addGap(12, 12, 12)
                                .addComponent(emailEditFunc2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EspecialidadeEditFunc2)
                                .addGap(12, 12, 12)
                                .addComponent(especialidadeEditFunc2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SalarioEditFunc2)
                                .addGap(12, 12, 12)
                                .addComponent(salarioEditFunc2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ConfirmaEditFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(CancelaEditFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
            .addComponent(Titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeEditFunc1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(nomeEditFunc1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CPFEditFunc1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(cpfEditFunc1)))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EspecialidadeEditFunc1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(especialidadeEditFunc1)))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SalarioEditFunc1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(salarioEditFunc1))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SetaEditFunc)))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TelefoneEditFunc1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(telefoneEditFunc1)))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailEditFunc1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(emailEditFunc1))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeEditFunc2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(nomeEditFunc2)))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CPFEditFunc2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(cpfEditFunc2)))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EspecialidadeEditFunc2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(especialidadeEditFunc2)))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SalarioEditFunc2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(salarioEditFunc2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TelefoneEditFunc2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(telefoneEditFunc2)))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmaiEditFunc2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(emailEditFunc2)))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConfirmaEditFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelaEditFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmaEditFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmaEditFuncActionPerformed
       try {
           // Click no Botão Sim:
           
           funcionarioBanco.altera(funcionario_novo);
           
           dispose();
           JOptionPane.showMessageDialog(null, "Funcionário Editado com Sucesso!!!");
           
           opf.Limpar();
       } catch (Exception ex) {
            Logger.getLogger(EditFuncAlerta.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(null, "Não foi possível alterar o funcionário");
       }
    }//GEN-LAST:event_ConfirmaEditFuncActionPerformed

    private void CancelaEditFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelaEditFuncActionPerformed
        // Click no Botão Cancelar:

        dispose();
    }//GEN-LAST:event_CancelaEditFuncActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Quando Abre a Janela

        //Antes
        nomeEditFunc1.setText(funcionario_antigo.getNome());
        cpfEditFunc1.setText(funcionario_antigo.getCPF());
        especialidadeEditFunc1.setText(funcionario_antigo.getEspecialidade());
        emailEditFunc1.setText(funcionario_antigo.getEmail());
        telefoneEditFunc1.setText(funcionario_antigo.getTelefone());
        salarioEditFunc1.setText(String.valueOf(funcionario_antigo.getSalario()));

        //Depois
        
        nomeEditFunc2.setText(funcionario_novo.getNome());
        cpfEditFunc2.setText(funcionario_novo.getCPF());
        especialidadeEditFunc2.setText(funcionario_novo.getEspecialidade());
        emailEditFunc2.setText(funcionario_novo.getEmail());
        telefoneEditFunc2.setText(funcionario_novo.getTelefone());
        salarioEditFunc2.setText(String.valueOf(funcionario_novo.getSalario()));
        

    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPFEditFunc1;
    private javax.swing.JLabel CPFEditFunc2;
    private javax.swing.JButton CancelaEditFunc;
    private javax.swing.JButton ConfirmaEditFunc;
    private javax.swing.JLabel EmaiEditFunc2;
    private javax.swing.JLabel EmailEditFunc1;
    private javax.swing.JLabel EspecialidadeEditFunc1;
    private javax.swing.JLabel EspecialidadeEditFunc2;
    private javax.swing.JLabel NomeEditFunc1;
    private javax.swing.JLabel NomeEditFunc2;
    private javax.swing.JLabel SalarioEditFunc1;
    private javax.swing.JLabel SalarioEditFunc2;
    private javax.swing.JLabel SetaEditFunc;
    private javax.swing.JLabel TelefoneEditFunc1;
    private javax.swing.JLabel TelefoneEditFunc2;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel cpfEditFunc1;
    private javax.swing.JLabel cpfEditFunc2;
    private javax.swing.JLabel emailEditFunc1;
    private javax.swing.JLabel emailEditFunc2;
    private javax.swing.JLabel especialidadeEditFunc1;
    private javax.swing.JLabel especialidadeEditFunc2;
    private javax.swing.JLabel nomeEditFunc1;
    private javax.swing.JLabel nomeEditFunc2;
    private javax.swing.JLabel salarioEditFunc1;
    private javax.swing.JLabel salarioEditFunc2;
    private javax.swing.JLabel telefoneEditFunc1;
    private javax.swing.JLabel telefoneEditFunc2;
    // End of variables declaration//GEN-END:variables
}
