/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces.Administrador.AdmAluno;

import java.awt.Graphics2D;
import java.awt.GraphicsConfiguration;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetos.Aluno;
import objetos.Avaliacao;
import objetos.Nutricionista;
import objetos_dao.AlunoDAO;
import objetos_dao.AvaliacaoDAO;
import objetos_dao.NutricionistaDAO;

/**
 *
 * @author Marco Antônio
 */
public class OpAlunos extends javax.swing.JPanel {

    /** Creates new form Alunos */
    
    AlunoDAO alunoBanco =  new AlunoDAO();
    
  //  BancoFalso mestre = new BancoFalso();
    public static Aluno tempAlun = new Aluno();
    public static String extensao = "";
    public static int indice = -1;
    public OpAlunos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProcuraFoto = new javax.swing.JFileChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Titulo = new javax.swing.JLabel();
        TelaAlun = new javax.swing.JTabbedPane();
        AbaAlun = new javax.swing.JPanel();
        fotoAlun = new javax.swing.JLabel();
        TelefoneAlun = new javax.swing.JLabel();
        telefoneAlun = new javax.swing.JLabel();
        EmailAlun = new javax.swing.JLabel();
        emailAlun = new javax.swing.JLabel();
        NomeAlun = new javax.swing.JLabel();
        nomeAlun = new javax.swing.JLabel();
        CPFAlun = new javax.swing.JLabel();
        cpfAlun = new javax.swing.JLabel();
        SexoAlun = new javax.swing.JLabel();
        sexoAlun = new javax.swing.JLabel();
        NutriAlun = new javax.swing.JLabel();
        nutrAlun = new javax.swing.JLabel();
        DataPagaAlun = new javax.swing.JLabel();
        dataPagaAlun = new javax.swing.JLabel();
        DataNascAlun = new javax.swing.JLabel();
        dataNascAlun = new javax.swing.JLabel();
        AbaCadAlun = new javax.swing.JPanel();
        fotoCadAlun = new javax.swing.JLabel();
        AdicionarFotoAlun = new javax.swing.JButton();
        NomeCadAlun = new javax.swing.JLabel();
        nomeCadAlun = new javax.swing.JTextField();
        CPFCadAlun = new javax.swing.JLabel();
        NutriCadAlun = new javax.swing.JLabel();
        nutrCadAlun = new javax.swing.JComboBox<>();
        SexoCadAlun = new javax.swing.JLabel();
        DataNascCadAlun = new javax.swing.JLabel();
        dataNascCadAlun = new com.toedter.calendar.JDateChooser();
        TelefoneCadAlun = new javax.swing.JLabel();
        telefoneCadAlun = new javax.swing.JTextField();
        EmailCadAlun = new javax.swing.JLabel();
        emailCadAlun = new javax.swing.JTextField();
        DataPagaCadAlun = new javax.swing.JLabel();
        CadastrarAlun = new javax.swing.JButton();
        EditarAlun = new javax.swing.JButton();
        ExcluirAlun = new javax.swing.JButton();
        diaPagaCadAlun = new javax.swing.JSpinner();
        SexoM = new javax.swing.JRadioButton();
        SexoF = new javax.swing.JRadioButton();
        cpfCadAlun = new javax.swing.JFormattedTextField();
        AbaAvaliacaoAlun = new javax.swing.JPanel();
        dataAvaCadAlun = new com.toedter.calendar.JDateChooser();
        porcMasCadAlun = new javax.swing.JTextField();
        porcGorCadAlun = new javax.swing.JTextField();
        PorcGorCadAlun = new javax.swing.JLabel();
        PorcMasCadAlun = new javax.swing.JLabel();
        pesoCadAlun = new javax.swing.JTextField();
        PesoCadAlun = new javax.swing.JLabel();
        AltuCadAlun = new javax.swing.JLabel();
        altuCadAlun = new javax.swing.JTextField();
        cpfAvaAlun = new javax.swing.JLabel();
        CPFAvaAlun = new javax.swing.JLabel();
        NomeAvaAlun = new javax.swing.JLabel();
        nomeAvaAlun = new javax.swing.JLabel();
        fotoAvaAlun = new javax.swing.JLabel();
        SalvarAvaAlun = new javax.swing.JButton();
        ImprAvaAlun = new javax.swing.JButton();
        AltuCadAlun1 = new javax.swing.JLabel();
        ScrollTabelaAlun1 = new javax.swing.JScrollPane();
        TabelaAvaAlun = new javax.swing.JTable();
        NomeAvaAlun1 = new javax.swing.JLabel();
        TabelaPesquisaAlun = new javax.swing.JPanel();
        PesquisarAlun = new javax.swing.JButton();
        pesquisarAlun = new javax.swing.JTextField();
        ScrollTabelaAlun = new javax.swing.JScrollPane();
        TabelaAlun = new javax.swing.JTable();
        LimparFunc = new javax.swing.JButton();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        Titulo.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Gerenciar alunos");

        TelaAlun.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TelaAlun.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        AbaAlun.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        fotoAlun.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TelefoneAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        TelefoneAlun.setText("Telefone:");

        telefoneAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        telefoneAlun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        telefoneAlun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        EmailAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        EmailAlun.setText("Email:");

        emailAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        emailAlun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailAlun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        NomeAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeAlun.setText("Nome:");

        nomeAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        CPFAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CPFAlun.setText("CPF:");

        cpfAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        SexoAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        SexoAlun.setText("Sexo:");

        sexoAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        NutriAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NutriAlun.setText("Nutricionista: ");

        nutrAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        DataPagaAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        DataPagaAlun.setText("Dia de Pagamento");

        dataPagaAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        DataNascAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        DataNascAlun.setText("Data de Nasc:");

        dataNascAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout AbaAlunLayout = new javax.swing.GroupLayout(AbaAlun);
        AbaAlun.setLayout(AbaAlunLayout);
        AbaAlunLayout.setHorizontalGroup(
            AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaAlunLayout.createSequentialGroup()
                .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AbaAlunLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(fotoAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AbaAlunLayout.createSequentialGroup()
                            .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(AbaAlunLayout.createSequentialGroup()
                                    .addGap(115, 115, 115)
                                    .addComponent(TelefoneAlun))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaAlunLayout.createSequentialGroup()
                                    .addGap(127, 127, 127)
                                    .addComponent(EmailAlun)
                                    .addGap(34, 34, 34)))
                            .addGap(86, 86, 86))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaAlunLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(telefoneAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaAlunLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(emailAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaAlunLayout.createSequentialGroup()
                        .addComponent(NomeAlun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AbaAlunLayout.createSequentialGroup()
                        .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaAlunLayout.createSequentialGroup()
                                .addComponent(CPFAlun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cpfAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AbaAlunLayout.createSequentialGroup()
                                .addComponent(SexoAlun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sexoAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaAlunLayout.createSequentialGroup()
                                .addComponent(DataNascAlun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dataNascAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AbaAlunLayout.createSequentialGroup()
                                .addComponent(DataPagaAlun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dataPagaAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AbaAlunLayout.createSequentialGroup()
                        .addComponent(NutriAlun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nutrAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        AbaAlunLayout.setVerticalGroup(
            AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaAlunLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AbaAlunLayout.createSequentialGroup()
                        .addComponent(fotoAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(TelefoneAlun))
                    .addGroup(AbaAlunLayout.createSequentialGroup()
                        .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomeAlun)
                            .addComponent(nomeAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CPFAlun)
                                .addComponent(cpfAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DataPagaAlun)
                                .addComponent(dataPagaAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SexoAlun)
                            .addComponent(sexoAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DataNascAlun)
                            .addComponent(dataNascAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaAlunLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefoneAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EmailAlun))
                    .addGroup(AbaAlunLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(AbaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NutriAlun)
                            .addComponent(nutrAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TelaAlun.addTab("Alunos", AbaAlun);

        AbaCadAlun.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        fotoCadAlun.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        AdicionarFotoAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        AdicionarFotoAlun.setText("Adicionar");
        AdicionarFotoAlun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarFotoAlunActionPerformed(evt);
            }
        });

        NomeCadAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeCadAlun.setText("Nome:");

        nomeCadAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeCadAlun.setPreferredSize(new java.awt.Dimension(74, 32));

        CPFCadAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CPFCadAlun.setText("CPF:");

        NutriCadAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NutriCadAlun.setText("Nutricionista:");

        nutrCadAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        SexoCadAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        SexoCadAlun.setText("Sexo:");

        DataNascCadAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        DataNascCadAlun.setText("Data de Nasc:");

        dataNascCadAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        TelefoneCadAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        TelefoneCadAlun.setText("Telefone:");

        telefoneCadAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        telefoneCadAlun.setPreferredSize(new java.awt.Dimension(74, 32));

        EmailCadAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        EmailCadAlun.setText("Email:");

        emailCadAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        emailCadAlun.setPreferredSize(new java.awt.Dimension(74, 32));

        DataPagaCadAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        DataPagaCadAlun.setText("Dia de Pagamento:");

        CadastrarAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CadastrarAlun.setText("Cadastrar");
        CadastrarAlun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarAlunActionPerformed(evt);
            }
        });

        EditarAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        EditarAlun.setText("Editar");
        EditarAlun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarAlunActionPerformed(evt);
            }
        });

        ExcluirAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ExcluirAlun.setText("Excluir");
        ExcluirAlun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirAlunActionPerformed(evt);
            }
        });

        diaPagaCadAlun.setModel(new javax.swing.SpinnerNumberModel(1, 1, 25, 1));

        buttonGroup1.add(SexoM);
        SexoM.setText("Masculino");
        SexoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SexoMActionPerformed(evt);
            }
        });

        buttonGroup1.add(SexoF);
        SexoF.setText("Feminino");

        try {
            cpfCadAlun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout AbaCadAlunLayout = new javax.swing.GroupLayout(AbaCadAlun);
        AbaCadAlun.setLayout(AbaCadAlunLayout);
        AbaCadAlunLayout.setHorizontalGroup(
            AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCadAlunLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fotoCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdicionarFotoAlun))
                .addGap(18, 18, 18)
                .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaCadAlunLayout.createSequentialGroup()
                        .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaCadAlunLayout.createSequentialGroup()
                                .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AbaCadAlunLayout.createSequentialGroup()
                                        .addComponent(SexoCadAlun)
                                        .addGap(8, 8, 8)
                                        .addComponent(SexoF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SexoM))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AbaCadAlunLayout.createSequentialGroup()
                                        .addComponent(CPFCadAlun)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cpfCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(23, 23, 23)
                                .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AbaCadAlunLayout.createSequentialGroup()
                                        .addComponent(NutriCadAlun)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nutrCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(AbaCadAlunLayout.createSequentialGroup()
                                        .addComponent(DataNascCadAlun)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dataNascCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(AbaCadAlunLayout.createSequentialGroup()
                                .addComponent(NomeCadAlun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AbaCadAlunLayout.createSequentialGroup()
                                .addComponent(TelefoneCadAlun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefoneCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EmailCadAlun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ExcluirAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CadastrarAlun)
                            .addComponent(EditarAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AbaCadAlunLayout.createSequentialGroup()
                        .addComponent(DataPagaCadAlun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(diaPagaCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        AbaCadAlunLayout.setVerticalGroup(
            AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCadAlunLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(fotoCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AdicionarFotoAlun)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AbaCadAlunLayout.createSequentialGroup()
                .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaCadAlunLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomeCadAlun)
                            .addComponent(nomeCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nutrCadAlun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CPFCadAlun, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NutriCadAlun, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cpfCadAlun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SexoCadAlun)
                                .addComponent(DataNascCadAlun))
                            .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SexoF)
                                .addComponent(SexoM))
                            .addComponent(dataNascCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TelefoneCadAlun)
                            .addComponent(telefoneCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailCadAlun)
                            .addComponent(emailCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AbaCadAlunLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(CadastrarAlun)
                        .addGap(18, 18, 18)
                        .addComponent(EditarAlun)
                        .addGap(18, 18, 18)
                        .addComponent(ExcluirAlun)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AbaCadAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DataPagaCadAlun, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(diaPagaCadAlun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(210, 210, 210))
        );

        TelaAlun.addTab("Controle", AbaCadAlun);

        AbaAvaliacaoAlun.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        dataAvaCadAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        porcMasCadAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        porcMasCadAlun.setPreferredSize(new java.awt.Dimension(74, 32));

        porcGorCadAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        porcGorCadAlun.setPreferredSize(new java.awt.Dimension(74, 32));

        PorcGorCadAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        PorcGorCadAlun.setText("Porcentagem de Gordura:");

        PorcMasCadAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        PorcMasCadAlun.setText("Porcentagem de Massa:");

        pesoCadAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pesoCadAlun.setPreferredSize(new java.awt.Dimension(74, 32));

        PesoCadAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        PesoCadAlun.setText("Peso:");

        AltuCadAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        AltuCadAlun.setText("Altura:");

        altuCadAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        altuCadAlun.setPreferredSize(new java.awt.Dimension(74, 32));

        cpfAvaAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cpfAvaAlun.setText(" ");

        CPFAvaAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CPFAvaAlun.setText("CPF:");

        NomeAvaAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeAvaAlun.setText("Nome:");

        nomeAvaAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeAvaAlun.setText(" ");

        fotoAvaAlun.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SalvarAvaAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        SalvarAvaAlun.setText("Salvar ");
        SalvarAvaAlun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarAvaAlunActionPerformed(evt);
            }
        });

        ImprAvaAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ImprAvaAlun.setText("Imprimir");

        AltuCadAlun1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        AltuCadAlun1.setText("Data de Avaliação:");

        TabelaAvaAlun.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabelaAvaAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TabelaAvaAlun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaAvaAlun.setToolTipText("");
        TabelaAvaAlun.setAlignmentX(1.0F);
        TabelaAvaAlun.setAlignmentY(1.0F);
        TabelaAvaAlun.setRowHeight(28);
        TabelaAvaAlun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaAvaAlunMouseClicked(evt);
            }
        });
        ScrollTabelaAlun1.setViewportView(TabelaAvaAlun);

        NomeAvaAlun1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeAvaAlun1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeAvaAlun1.setText("Avaliações:");

        javax.swing.GroupLayout AbaAvaliacaoAlunLayout = new javax.swing.GroupLayout(AbaAvaliacaoAlun);
        AbaAvaliacaoAlun.setLayout(AbaAvaliacaoAlunLayout);
        AbaAvaliacaoAlunLayout.setHorizontalGroup(
            AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaAvaliacaoAlunLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaAvaliacaoAlunLayout.createSequentialGroup()
                        .addComponent(fotoAvaAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NomeAvaAlun)
                            .addComponent(CPFAvaAlun))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomeAvaAlun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cpfAvaAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AbaAvaliacaoAlunLayout.createSequentialGroup()
                        .addGroup(AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(AbaAvaliacaoAlunLayout.createSequentialGroup()
                                .addComponent(PesoCadAlun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pesoCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(AbaAvaliacaoAlunLayout.createSequentialGroup()
                                .addComponent(AltuCadAlun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(altuCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(AbaAvaliacaoAlunLayout.createSequentialGroup()
                                .addComponent(PorcGorCadAlun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(porcGorCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AbaAvaliacaoAlunLayout.createSequentialGroup()
                                .addComponent(PorcMasCadAlun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(porcMasCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AbaAvaliacaoAlunLayout.createSequentialGroup()
                        .addComponent(AltuCadAlun1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataAvaCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(NomeAvaAlun1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(ScrollTabelaAlun1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImprAvaAlun, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SalvarAvaAlun, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        AbaAvaliacaoAlunLayout.setVerticalGroup(
            AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaAvaliacaoAlunLayout.createSequentialGroup()
                .addGroup(AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AbaAvaliacaoAlunLayout.createSequentialGroup()
                        .addGroup(AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fotoAvaAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AbaAvaliacaoAlunLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NomeAvaAlun)
                                    .addComponent(nomeAvaAlun))
                                .addGap(18, 18, 18)
                                .addGroup(AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CPFAvaAlun)
                                    .addComponent(cpfAvaAlun))))
                        .addGap(18, 18, 18)
                        .addGroup(AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(AltuCadAlun)
                                .addComponent(altuCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(PorcGorCadAlun)
                                .addComponent(porcGorCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pesoCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PesoCadAlun))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(PorcMasCadAlun)
                                .addComponent(porcMasCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AltuCadAlun1)
                            .addComponent(dataAvaCadAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AbaAvaliacaoAlunLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SalvarAvaAlun)
                            .addComponent(NomeAvaAlun1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AbaAvaliacaoAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ImprAvaAlun)
                            .addComponent(ScrollTabelaAlun1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TelaAlun.addTab("Avaliação", AbaAvaliacaoAlun);

        TabelaPesquisaAlun.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PesquisarAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        PesquisarAlun.setText("Pesquisar");
        PesquisarAlun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarAlunActionPerformed(evt);
            }
        });

        pesquisarAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pesquisarAlun.setPreferredSize(new java.awt.Dimension(74, 32));

        TabelaAlun.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabelaAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TabelaAlun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Dia de Pagameno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaAlun.setToolTipText("");
        TabelaAlun.setAlignmentX(1.0F);
        TabelaAlun.setAlignmentY(1.0F);
        TabelaAlun.setRowHeight(28);
        TabelaAlun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaAlunMouseClicked(evt);
            }
        });
        ScrollTabelaAlun.setViewportView(TabelaAlun);

        LimparFunc.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        LimparFunc.setText("Limpar");
        LimparFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TabelaPesquisaAlunLayout = new javax.swing.GroupLayout(TabelaPesquisaAlun);
        TabelaPesquisaAlun.setLayout(TabelaPesquisaAlunLayout);
        TabelaPesquisaAlunLayout.setHorizontalGroup(
            TabelaPesquisaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelaPesquisaAlunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PesquisarAlun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesquisarAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LimparFunc)
                .addContainerGap())
            .addGroup(TabelaPesquisaAlunLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ScrollTabelaAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TabelaPesquisaAlunLayout.setVerticalGroup(
            TabelaPesquisaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelaPesquisaAlunLayout.createSequentialGroup()
                .addGroup(TabelaPesquisaAlunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PesquisarAlun)
                    .addComponent(pesquisarAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LimparFunc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(ScrollTabelaAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TabelaPesquisaAlun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelaAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TelaAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabelaPesquisaAlun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AdicionarFotoAlunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarFotoAlunActionPerformed
        // Adicionar Foto

        String foto;
        ProcuraFoto.showOpenDialog(this);
        File arquivo = ProcuraFoto.getSelectedFile();

        try {

            if (arquivo != null) {
                foto = (arquivo.getPath());
                extensao = getFileExtension(arquivo);
                ImageIcon imageIcon = new ImageIcon(foto); // load the image to a imageIcon
                Image image = imageIcon.getImage(); // transform it
                Image newimg = image.getScaledInstance(100, 110,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
                imageIcon = new ImageIcon(newimg);

                fotoCadAlun.setIcon(imageIcon);
                foto = (fotoCadAlun.getIcon().toString());

            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Selecione uma Imagem Valida!!!");
        }
    }//GEN-LAST:event_AdicionarFotoAlunActionPerformed

    private void CadastrarAlunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarAlunActionPerformed
        // Botão Cadastrar
        try {

            if( nomeCadAlun.getText().isBlank() ||
                cpfCadAlun.getText().isBlank() ||
                buttonGroup1.getSelection() == null ||
                dataNascCadAlun.getDate() == null ||
                telefoneCadAlun.getText().isBlank() ||
                !isValidEmailAddress(emailCadAlun.getText())){
                throw new Exception();
            }

            boolean i = true;
            tempAlun = new Aluno();
            tempAlun.setNome(nomeCadAlun.getText());
            tempAlun.setCPF(cpfCadAlun.getText());

            if(SexoF.isSelected())
                tempAlun.setSexo('F');
            else
                tempAlun.setSexo('M');

            if(nutrCadAlun.getSelectedItem() == null)
                tempAlun.setNutricionista(null);
            else
                tempAlun.setNutricionista((Nutricionista)nutrCadAlun.getSelectedItem());
            tempAlun.setDt_nascimento(new Date(dataNascCadAlun.getDate().getTime()));
            tempAlun.setDia_pagamento((Integer)diaPagaCadAlun.getValue());
            tempAlun.setTelefone(telefoneCadAlun.getText());
            tempAlun.setEmail(emailCadAlun.getText());

            tempAlun.setImagem(iconToByte(new ImageIcon(iconToImage(fotoCadAlun.getIcon()))));

            ArrayList<Aluno> alunos = alunoBanco.getLista();

            for (Aluno a : alunos) {

                if (a.getCPF().equals(cpfCadAlun.getText())) {

                    JOptionPane.showMessageDialog(null, "Aluno já Existente!!!");
                    i = false;
                }
            }

            if (i || alunos.isEmpty()) {

                alunoBanco.adiciona(tempAlun);
                JOptionPane.showMessageDialog(null, "Aluno Cadastrado com Sucesso!");
                LimparFuncActionPerformed(evt);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_CadastrarAlunActionPerformed

    private void EditarAlunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarAlunActionPerformed
        // Botão Editar

        try {
            if (indice >= 0 && !cpfCadAlun.getText().isEmpty()) {

                if( nomeCadAlun.getText().isBlank() ||
                    cpfCadAlun.getText().isBlank() ||
                    buttonGroup1.getSelection() == null ||
                    dataNascCadAlun.getDate() == null ||
                    telefoneCadAlun.getText().isBlank() ||
                    !isValidEmailAddress(emailCadAlun.getText())){
                    throw new Exception("Verifique se os campos estão preenchidos corretamente");
                }

                tempAlun = new Aluno();
                tempAlun.setNome(nomeCadAlun.getText());
                tempAlun.setCPF(cpfCadAlun.getText());
                if(SexoF.isSelected())
                    tempAlun.setSexo('F');
                else
                    tempAlun.setSexo('M');

                tempAlun.setNutricionista((Nutricionista)nutrCadAlun.getSelectedItem());
                tempAlun.setDt_nascimento(new Date(dataNascCadAlun.getDate().getTime()));
                tempAlun.setDia_pagamento((Integer)diaPagaCadAlun.getValue());
                tempAlun.setTelefone(telefoneCadAlun.getText());
                tempAlun.setEmail(emailCadAlun.getText());

                tempAlun.setImagem(iconToByte(new ImageIcon(iconToImage(fotoCadAlun.getIcon()))));

                EditAlunAlerta EAA = new EditAlunAlerta(alunoBanco.getAluno(tempAlun.getCPF()), tempAlun, this);
                EAA.setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_EditarAlunActionPerformed

    private void ExcluirAlunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirAlunActionPerformed
        // Botão Excluir Funcionario

        try {

            if (indice >= 0 && !cpfCadAlun.getText().isEmpty()) {

                tempAlun = alunoBanco.getAluno(cpfAlun.getText());

                ExcAlunAlerta EAA = new ExcAlunAlerta(tempAlun, this);
                EAA.setVisible(true);

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Selecione um aluno válido na tabela!!!");
            indice = -1;
        }
    }//GEN-LAST:event_ExcluirAlunActionPerformed

    private void SexoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SexoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SexoMActionPerformed

    private void PesquisarAlunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarAlunActionPerformed
        try {
            // Botão Pesquisar Funcionário
            
            DefaultTableModel TF = (DefaultTableModel) TabelaAlun.getModel();
            TF.setNumRows(0);
            
            ArrayList<Aluno> alunos = alunoBanco.getLista();
            
            for (int i = 0; i < alunos.size(); i++) {
                
                if (alunos.get(i).getCPF().contains(pesquisarAlun.getText()) || alunos.get(i).getNome().contains(pesquisarAlun.getText())) {
                    
                    TF.addRow(new Object[]{
                        alunos.get(i).getNome(),
                        alunos.get(i).getCPF(),
                        alunos.get(i).getDia_pagamento(),});
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(OpAlunos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PesquisarAlunActionPerformed

    private void TabelaAlunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaAlunMouseClicked
        // Ao Clicar na Tabela

        indice = TabelaAlun.getSelectedRow();

        String CPF = TabelaAlun.getValueAt(indice, 1).toString();
        System.out.println(CPF);

        try {
            if (indice >= 0 && CPF != null) {
                Aluno aluno = alunoBanco.getAluno(CPF);
                //Aluno
                nomeAlun.setText(aluno.getNome());
                cpfAlun.setText(aluno.getCPF());
                if(aluno.getSexo() == 'F' || aluno.getSexo() == 'f')
                    sexoAlun.setText("Feminino");
                else
                    sexoAlun.setText("Masculino");                
                dataNascAlun.setText(new SimpleDateFormat("dd/MM/yyyy").format(aluno.getDt_nascimento()));
                dataPagaAlun.setText(String.valueOf(aluno.getDia_pagamento()));
                telefoneAlun.setText(aluno.getTelefone());
                emailAlun.setText(aluno.getEmail());
                
                if(aluno.getImagem() == null)
                    fotoAlun.setIcon(iconScale(new ImageIcon(getClass().getResource("/Imagens/Perfil.png"))));
                else
                    fotoAlun.setIcon(new ImageIcon(aluno.getImagem()));

                //Controle
                nomeCadAlun.setText(aluno.getNome());
                cpfCadAlun.setText(aluno.getCPF());
                
                if(aluno.getSexo() == 'F' || aluno.getSexo() == 'f')
                    SexoF.setSelected(true);
                else
                    SexoM.setSelected(true);  
                
                if(aluno.getNutricionista() != null){
                    nutrCadAlun.setSelectedItem(aluno.getNutricionista());
                    nutrAlun.setText(aluno.getNutricionista().getNome());
                } else {
                    nutrCadAlun.setSelectedItem(null);
                    nutrAlun.setText("Nenhum");
                }
                
                dataNascCadAlun.setDate(new java.util.Date(aluno.getDt_nascimento().getTime()));
                diaPagaCadAlun.setValue(aluno.getDia_pagamento());
                telefoneCadAlun.setText(aluno.getTelefone());
                emailCadAlun.setText(aluno.getEmail());
                
                if(aluno.getImagem() == null)
                    fotoCadAlun.setIcon(iconScale(new ImageIcon(getClass().getResource("/Imagens/Perfil.png"))));
                else
                    fotoCadAlun.setIcon(new ImageIcon(aluno.getImagem()));

                //Recibo
//                nomeRecAlun.setText(aluno.getNome());
//                precoRecAlun.setText("R$ Valor");

                cpfCadAlun.setEditable(false);
                CadastrarAlun.setEnabled(false);
                EditarAlun.setEnabled(true);
                ExcluirAlun.setEnabled(true);
                
                //Avaliação
                if (aluno.getImagem() == null) {
                    fotoAvaAlun.setIcon(iconScale(new ImageIcon(getClass().getResource("/Imagens/Perfil.png"))));
                } else {
                    fotoAvaAlun.setIcon(new ImageIcon(aluno.getImagem()));
                }

                nomeAvaAlun.setText(aluno.getNome());
                cpfAvaAlun.setText(aluno.getCPF());
                altuCadAlun.setText("");
                pesoCadAlun.setText("");
                porcGorCadAlun.setText("");
                porcMasCadAlun.setText("");

                AtualizaTabelaAva();

            } else {

                JOptionPane.showMessageDialog(null, "Selecione o Aluno na Tabela!!!");
                indice = -1;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            Logger.getLogger(OpAlunos.class.getName()).log(Level.SEVERE, null, e);
            indice = -1;
        }
    }//GEN-LAST:event_TabelaAlunMouseClicked

    
    
    
    private void LimparFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparFuncActionPerformed
        Limpar();
    }//GEN-LAST:event_LimparFuncActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        try {
            AtualizaTabela();
            NutricionistaDAO nutricionistaBanco = new NutricionistaDAO();
            ArrayList<Nutricionista> nutricionistas = nutricionistaBanco.getLista();
            
            fotoAlun.setIcon(iconScale(new ImageIcon(getClass().getResource("/Imagens/Perfil.png"))));
            fotoCadAlun.setIcon(iconScale(new ImageIcon(getClass().getResource("/Imagens/Perfil.png"))));
            extensao = "png";
            
            EditarAlun.setEnabled(false);
            ExcluirAlun.setEnabled(false);
            
            nutrCadAlun.addItem(null);
            
            for (int i = 0; i < nutricionistas.size(); i++) {                
                nutrCadAlun.addItem(nutricionistas.get(i));
                
            }
        } catch (Exception ex) {
            Logger.getLogger(OpAlunos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formAncestorAdded

    private void SalvarAvaAlunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarAvaAlunActionPerformed
        // Salvar Avaliação

        indice = TabelaAlun.getSelectedRow();
        String CPF = TabelaAlun.getValueAt(indice, 1).toString();
        AvaliacaoDAO avaliacaoBanco = new AvaliacaoDAO();
        Avaliacao avaTemp = new Avaliacao();

        try {
            if (indice >= 0 && CPF != null) {

                Aluno aluno = alunoBanco.getAluno(CPF);

                avaTemp.setAluno(aluno);
                avaTemp.setAltura(Float.valueOf(altuCadAlun.getText()));
                avaTemp.setData(new Date(dataAvaCadAlun.getDate().getTime()));
                avaTemp.setPeso(Float.valueOf(pesoCadAlun.getText()));
                avaTemp.setPorcentagem_gordura(Float.valueOf(porcGorCadAlun.getText()));
                avaTemp.setPorcentagem_massa(Float.valueOf(porcMasCadAlun.getText()));
                avaliacaoBanco.adiciona(avaTemp);
                AtualizaTabelaAva();

            }
        } catch (NumberFormatException | IndexOutOfBoundsException e) {

            JOptionPane.showMessageDialog(null, "Selecione um Aluno Valido!!!");
            indice = -1;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível registrar esta avaliação. Verifique se existem conflitos de data");
        }
    }//GEN-LAST:event_SalvarAvaAlunActionPerformed

    private void TabelaAvaAlunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaAvaAlunMouseClicked
        // Ao Clicar na Tabela

        indice = TabelaAlun.getSelectedRow();
        int indice2 = TabelaAvaAlun.getSelectedRow();

        String CPF = TabelaAlun.getValueAt(indice, 1).toString();

        try {
            if (indice >= 0 && CPF != null) {

                Aluno aluno = alunoBanco.getAluno(CPF);
                AvaliacaoDAO avaliacaoBanco = new AvaliacaoDAO();

                altuCadAlun.setText(String.valueOf(avaliacaoBanco.getAvaliacao(aluno.getCPF()).get(indice2).getAltura()));
                pesoCadAlun.setText(String.valueOf(avaliacaoBanco.getAvaliacao(aluno.getCPF()).get(indice2).getPeso()));
                porcGorCadAlun.setText(String.valueOf(avaliacaoBanco.getAvaliacao(aluno.getCPF()).get(indice2).getPorcentagem_gordura()));
                porcMasCadAlun.setText(String.valueOf(avaliacaoBanco.getAvaliacao(aluno.getCPF()).get(indice2).getPorcentagem_massa()));
                dataAvaCadAlun.setDate(new java.util.Date(avaliacaoBanco.getAvaliacao(aluno.getCPF()).get(indice2).getData().getTime()));

            } else {

                JOptionPane.showMessageDialog(null, "Selecione a avaliação na tabela");
                indice = -1;
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Selecione uma avaliação válida");
            indice = -1;
        }
    }//GEN-LAST:event_TabelaAvaAlunMouseClicked

    public void Limpar(){
        //Aluno
        nomeAlun.setText("");
        cpfAlun.setText("");
        sexoAlun.setText("");
        nutrAlun.setText("");
        dataNascAlun.setText("");
        dataPagaAlun.setText("");
        telefoneAlun.setText("");
        emailAlun.setText("");

        fotoAlun.setIcon(iconScale(new ImageIcon(getClass().getResource("/Imagens/Perfil.png"))));

        //Controle
        nomeCadAlun.setText("");
        cpfCadAlun.setText("");
        buttonGroup1.clearSelection();
        nutrCadAlun.setSelectedItem(null);
        dataNascCadAlun.setDate(null);
        diaPagaCadAlun.setValue(1);
        telefoneCadAlun.setText("");
        emailCadAlun.setText("");

        fotoCadAlun.setIcon(iconScale(new ImageIcon(getClass().getResource("/Imagens/Perfil.png"))));

        //Recibo
//        nomeRecAlun.setText("");
//        precoRecAlun.setText("");
//        dataRecAlun.setDateFormatString("");
        
        extensao = "png";
        
        cpfCadAlun.setEditable(true);
        
        CadastrarAlun.setEnabled(true);
        EditarAlun.setEnabled(false);
        ExcluirAlun.setEnabled(false);

        //Atualiza a Tabela
        AtualizaTabela();
        
        fotoAvaAlun.setIcon(iconScale(new ImageIcon(getClass().getResource("/Imagens/Perfil.png"))));
        nomeAvaAlun.setText(" ");
        cpfAvaAlun.setText(" ");
        altuCadAlun.setText(" ");
        pesoCadAlun.setText(" ");
        porcGorCadAlun.setText(" ");
        porcMasCadAlun.setText(" ");
        dataAvaCadAlun.setDateFormatString(" ");
    }  
    
    public void AtualizaTabela() {

        try {
            DefaultTableModel TF = (DefaultTableModel) TabelaAlun.getModel();
            TF.setNumRows(0);
            
            ArrayList<Aluno> alunos = alunoBanco.getLista();
            
            for (int i = 0; i < alunos.size(); i++) {
                
                TF.addRow(new Object[]{
                    alunos.get(i).getNome(),
                    alunos.get(i).getCPF(),
                    alunos.get(i).getDia_pagamento(),});
            }
        } catch (Exception ex) {
            Logger.getLogger(OpAlunos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void AtualizaTabelaAva() {

        indice = TabelaAlun.getSelectedRow();
        String CPF = TabelaAlun.getValueAt(indice, 1).toString();

        AvaliacaoDAO avaliacaoBanco = new AvaliacaoDAO();

        DefaultTableModel TAA = (DefaultTableModel) TabelaAvaAlun.getModel();
        TAA.setNumRows(0);

        try {
            if (indice >= 0 && CPF != null) {

                Aluno aluno = alunoBanco.getAluno(CPF);

                for (int i = 0; i < avaliacaoBanco.getAvaliacao(aluno.getCPF()).size(); i++) {

                    TAA.addRow(new Object[]{avaliacaoBanco.getAvaliacao(aluno.getCPF()).get(i).getData()});
                }

            } else {

                JOptionPane.showMessageDialog(null, "Selecione o Aluno na Tabela!!!");
                indice = -1;
            }

        } catch (Exception ex) {
            Logger.getLogger(OpAlunos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    public byte[] iconToByte(ImageIcon icon){
        
        BufferedImage bi = getBufferedImage(icon.getImage());
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        
        try {
            ImageIO.write(bi, "png" , baos);
        } catch (IOException ex) {
            Logger.getLogger(OpAlunos.class.getName()).log(Level.SEVERE, null, ex);
        }

        byte[] byteArray= baos.toByteArray();
        return byteArray;
    }
    
    
    public static BufferedImage getBufferedImage(Image img)
    {
        if (img instanceof BufferedImage)
        {
           return (BufferedImage) img;
        }

        BufferedImage bimage = new BufferedImage(img.getWidth(null), 
                        img.getHeight(null), BufferedImage.TYPE_INT_ARGB);

        Graphics2D bGr = bimage.createGraphics();
        bGr.drawImage(img, 0, 0, null);
        bGr.dispose();

        // Return the buffered image
        return bimage;
    }
    
    static Image iconToImage(Icon icon) {
        if (icon instanceof ImageIcon) {
           return ((ImageIcon)icon).getImage();
        } 
        else {
           int w = icon.getIconWidth();
           int h = icon.getIconHeight();
           GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
           GraphicsDevice gd = ge.getDefaultScreenDevice();
           GraphicsConfiguration gc = gd.getDefaultConfiguration();
           BufferedImage image = gc.createCompatibleImage(w, h);
           Graphics2D g = image.createGraphics();
           icon.paintIcon(null, g, 0, 0);
           g.dispose();
           return image;
        }
 }   
    
    private static String getFileExtension(File file) {
        String fileName = file.getName();
        if(fileName.lastIndexOf(".") != -1 && fileName.lastIndexOf(".") != 0)
        return fileName.substring(fileName.lastIndexOf(".")+1);
        else return "";
    }
    
    public static ImageIcon iconScale(ImageIcon imageIcon){
        
        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(100, 110,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        imageIcon = new ImageIcon(newimg);
        
        return imageIcon;
    }
    
    public boolean isValidEmailAddress(String email) {
           String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
           java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
           java.util.regex.Matcher m = p.matcher(email);
           return m.matches();
    }
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AbaAlun;
    private javax.swing.JPanel AbaAvaliacaoAlun;
    private javax.swing.JPanel AbaCadAlun;
    private javax.swing.JButton AdicionarFotoAlun;
    private javax.swing.JLabel AltuCadAlun;
    private javax.swing.JLabel AltuCadAlun1;
    private javax.swing.JLabel CPFAlun;
    private javax.swing.JLabel CPFAvaAlun;
    private javax.swing.JLabel CPFCadAlun;
    private javax.swing.JButton CadastrarAlun;
    private javax.swing.JLabel DataNascAlun;
    private javax.swing.JLabel DataNascCadAlun;
    private javax.swing.JLabel DataPagaAlun;
    private javax.swing.JLabel DataPagaCadAlun;
    private javax.swing.JButton EditarAlun;
    private javax.swing.JLabel EmailAlun;
    private javax.swing.JLabel EmailCadAlun;
    private javax.swing.JButton ExcluirAlun;
    private javax.swing.JButton ImprAvaAlun;
    private javax.swing.JButton LimparFunc;
    private javax.swing.JLabel NomeAlun;
    private javax.swing.JLabel NomeAvaAlun;
    private javax.swing.JLabel NomeAvaAlun1;
    private javax.swing.JLabel NomeCadAlun;
    private javax.swing.JLabel NutriAlun;
    private javax.swing.JLabel NutriCadAlun;
    private javax.swing.JLabel PesoCadAlun;
    private javax.swing.JButton PesquisarAlun;
    private javax.swing.JLabel PorcGorCadAlun;
    private javax.swing.JLabel PorcMasCadAlun;
    private javax.swing.JFileChooser ProcuraFoto;
    private javax.swing.JButton SalvarAvaAlun;
    private javax.swing.JScrollPane ScrollTabelaAlun;
    private javax.swing.JScrollPane ScrollTabelaAlun1;
    private javax.swing.JLabel SexoAlun;
    private javax.swing.JLabel SexoCadAlun;
    private javax.swing.JRadioButton SexoF;
    private javax.swing.JRadioButton SexoM;
    private javax.swing.JTable TabelaAlun;
    private javax.swing.JTable TabelaAvaAlun;
    private javax.swing.JPanel TabelaPesquisaAlun;
    private javax.swing.JTabbedPane TelaAlun;
    private javax.swing.JLabel TelefoneAlun;
    private javax.swing.JLabel TelefoneCadAlun;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField altuCadAlun;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cpfAlun;
    private javax.swing.JLabel cpfAvaAlun;
    private javax.swing.JFormattedTextField cpfCadAlun;
    private com.toedter.calendar.JDateChooser dataAvaCadAlun;
    private javax.swing.JLabel dataNascAlun;
    private com.toedter.calendar.JDateChooser dataNascCadAlun;
    private javax.swing.JLabel dataPagaAlun;
    private javax.swing.JSpinner diaPagaCadAlun;
    private javax.swing.JLabel emailAlun;
    private javax.swing.JTextField emailCadAlun;
    private javax.swing.JLabel fotoAlun;
    private javax.swing.JLabel fotoAvaAlun;
    private javax.swing.JLabel fotoCadAlun;
    private javax.swing.JLabel nomeAlun;
    private javax.swing.JLabel nomeAvaAlun;
    private javax.swing.JTextField nomeCadAlun;
    private javax.swing.JLabel nutrAlun;
    private javax.swing.JComboBox<Nutricionista> nutrCadAlun;
    private javax.swing.JTextField pesoCadAlun;
    private javax.swing.JTextField pesquisarAlun;
    private javax.swing.JTextField porcGorCadAlun;
    private javax.swing.JTextField porcMasCadAlun;
    private javax.swing.JLabel sexoAlun;
    private javax.swing.JLabel telefoneAlun;
    private javax.swing.JTextField telefoneCadAlun;
    // End of variables declaration//GEN-END:variables

}
