/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Visualizar;

import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import objetos.Pagamento;
import objetos_dao.PagamentoDAO;

/**
 *
 * @author Marco Antônio
 */
public class ViewPagamentoMulta extends javax.swing.JPanel {

    /**
     * Creates new form OpAlunoExerc
     */
    
    
    public ViewPagamentoMulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        painelTurmas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePagamento = new javax.swing.JTable();
        Equipamentos = new javax.swing.JLabel();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        Titulo.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Pagamentos com multa");

        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        tablePagamento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tablePagamento.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tablePagamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Aluno", "Data", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePagamento.setRowHeight(28);
        jScrollPane2.setViewportView(tablePagamento);

        Equipamentos.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Equipamentos.setText("Pagamentos");

        javax.swing.GroupLayout painelTurmasLayout = new javax.swing.GroupLayout(painelTurmas);
        painelTurmas.setLayout(painelTurmasLayout);
        painelTurmasLayout.setHorizontalGroup(
            painelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTurmasLayout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(Equipamentos)
                .addContainerGap(414, Short.MAX_VALUE))
            .addGroup(painelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelTurmasLayout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(45, Short.MAX_VALUE)))
        );
        painelTurmasLayout.setVerticalGroup(
            painelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelTurmasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Equipamentos)
                .addContainerGap(457, Short.MAX_VALUE))
            .addGroup(painelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTurmasLayout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(jScrollPane2)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Visualizar", painelTurmas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        try {
            DefaultTableModel TF = (DefaultTableModel) tablePagamento.getModel();
            TF.setNumRows(0);
            
            for(Pagamento p : new PagamentoDAO().getListaMulta()){
                TF.addRow(new Object[]{
                    p.getAluno().getNome(),
                    new SimpleDateFormat("dd/MM/yyyy").format(p.getData()),
                    "R$ " + String.format("%.2f", p.getValor()),});        
            }
        } catch (Exception ex) {
            
        }
    }//GEN-LAST:event_formAncestorAdded

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Equipamentos;
    private javax.swing.JLabel Titulo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel painelTurmas;
    private javax.swing.JTable tablePagamento;
    // End of variables declaration//GEN-END:variables

}
