/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Visualizar;

import Interfaces.Instrutor.InstAluno.*;
import static Interfaces.Principal.Login.funcionarioLogin;
import Objetos_DAO.EquipamentoDAO;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetos.Aluno;
import objetos.Avaliacao;
import objetos.Equipamento;
import objetos.Exercicio;
import objetos.Turma;
import objetos_dao.AvaliacaoDAO;
import objetos_dao.ExercicioDAO;
import objetos_dao.TurmaDAO;
import objetos_dao.Turma_AlunoDAO;

/**
 *
 * @author Marco Antônio
 */
public class ViewEquipTurma extends javax.swing.JPanel {

    /**
     * Creates new form OpAlunoExerc
     */
    
    ArrayList<Aluno> tempAlunos;
    Aluno tempAluno;
    Exercicio tempExercicio;
    
    public ViewEquipTurma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        painelTurmas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTurmas = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableEquipamentos = new javax.swing.JTable();
        Turmas = new javax.swing.JLabel();
        Equipamentos = new javax.swing.JLabel();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        Titulo.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Equipamentos por turma");

        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        tableTurmas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tableTurmas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "N. Alunos", "Instrutor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTurmas.setRowHeight(28);
        tableTurmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTurmasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableTurmas);

        tableEquipamentos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tableEquipamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nome do Equipamento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEquipamentos.setRowHeight(28);
        jScrollPane3.setViewportView(tableEquipamentos);

        Turmas.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Turmas.setText("Turmas");

        Equipamentos.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Equipamentos.setText("Equipamentos");

        javax.swing.GroupLayout painelTurmasLayout = new javax.swing.GroupLayout(painelTurmas);
        painelTurmas.setLayout(painelTurmasLayout);
        painelTurmasLayout.setHorizontalGroup(
            painelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTurmasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(painelTurmasLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(Turmas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Equipamentos)
                .addGap(156, 156, 156))
        );
        painelTurmasLayout.setVerticalGroup(
            painelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelTurmasLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(painelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Turmas)
                    .addComponent(Equipamentos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Visualizar", painelTurmas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        try {
            DefaultTableModel TF = (DefaultTableModel) tableTurmas.getModel();
            TF.setNumRows(0);
            
            ((DefaultTableModel)tableEquipamentos.getModel()).setNumRows(0);
            
            for(Turma t : new TurmaDAO().getLista()){
                TF.addRow(new Object[]{
                    t.getId(),
                    new Turma_AlunoDAO().qtdAlunos(t.getId()),
                    t.getInstrutor().getNome(),});
            }
            
        } catch (Exception ex) {
            Logger.getLogger(ViewEquipTurma.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formAncestorAdded

    private void tableTurmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTurmasMouseClicked
        try {
            if(!(tableTurmas.getSelectedRow() >= 0))
                throw new Exception("Selecione uma turma válida na tabela");
            
            DefaultTableModel TF = (DefaultTableModel) tableEquipamentos.getModel();
            TF.setNumRows(0);
            
            for(String equip : new TurmaDAO().equipamentosTurmas((int) tableTurmas.getValueAt(tableTurmas.getSelectedRow(), 0))){
                TF.addRow(new Object[]{
                    equip,});
            }
            
        } catch (Exception ex) {
            Logger.getLogger(ViewEquipTurma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tableTurmasMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Equipamentos;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Turmas;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel painelTurmas;
    private javax.swing.JTable tableEquipamentos;
    private javax.swing.JTable tableTurmas;
    // End of variables declaration//GEN-END:variables

}
