/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Visualizar;

import Interfaces.Instrutor.InstAluno.*;
import static Interfaces.Principal.Login.funcionarioLogin;
import Objetos_DAO.EquipamentoDAO;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetos.Aluno;
import objetos.Avaliacao;
import objetos.Equipamento;
import objetos.Exercicio;
import objetos.Turma;
import objetos_dao.AlunoDAO;
import objetos_dao.AvaliacaoDAO;
import objetos_dao.ExercicioDAO;
import objetos_dao.TurmaDAO;
import objetos_dao.Turma_AlunoDAO;

/**
 *
 * @author Marco Antônio
 */
public class ViewFichaExercicio extends javax.swing.JPanel {

    /**
     * Creates new form OpAlunoExerc
     */
    
    AlunoDAO alunoBanco = new AlunoDAO();
    
    ArrayList<Aluno> tempAlunos;
    Aluno tempAluno;
    Exercicio tempExercicio;
    
    public ViewFichaExercicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        painelTurmas = new javax.swing.JPanel();
        Turmas = new javax.swing.JLabel();
        Equipamentos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableExercicios = new javax.swing.JTable();
        ScrollTabelaAlun = new javax.swing.JScrollPane();
        tableAluno = new javax.swing.JTable();
        pesquisarAlun = new javax.swing.JTextField();
        PesquisarAlun = new javax.swing.JButton();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        Titulo.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Exercícios do aluno");

        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        Turmas.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Turmas.setText("Alunos");

        Equipamentos.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Equipamentos.setText("Exercícios");

        tableExercicios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tableExercicios.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tableExercicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Exercício", "Repetições", "Equipamento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableExercicios.setRowHeight(28);
        jScrollPane1.setViewportView(tableExercicios);

        tableAluno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tableAluno.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tableAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableAluno.setToolTipText("");
        tableAluno.setAlignmentX(1.0F);
        tableAluno.setAlignmentY(1.0F);
        tableAluno.setRowHeight(28);
        tableAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAlunoMouseClicked(evt);
            }
        });
        ScrollTabelaAlun.setViewportView(tableAluno);

        pesquisarAlun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pesquisarAlun.setPreferredSize(new java.awt.Dimension(74, 32));

        PesquisarAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        PesquisarAlun.setText("Pesquisar");
        PesquisarAlun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarAlunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelTurmasLayout = new javax.swing.GroupLayout(painelTurmas);
        painelTurmas.setLayout(painelTurmasLayout);
        painelTurmasLayout.setHorizontalGroup(
            painelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTurmasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(painelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelTurmasLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(Turmas))
                    .addComponent(ScrollTabelaAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelTurmasLayout.createSequentialGroup()
                        .addComponent(PesquisarAlun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisarAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(painelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelTurmasLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(Equipamentos)
                        .addGap(184, 184, 184))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        painelTurmasLayout.setVerticalGroup(
            painelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelTurmasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelTurmasLayout.createSequentialGroup()
                        .addComponent(Turmas)
                        .addGap(18, 18, 18)
                        .addComponent(ScrollTabelaAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(painelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PesquisarAlun)
                            .addComponent(pesquisarAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelTurmasLayout.createSequentialGroup()
                        .addComponent(Equipamentos)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))))
        );

        jTabbedPane1.addTab("Visualizar", painelTurmas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        try {
            DefaultTableModel TF = (DefaultTableModel) tableAluno.getModel();
            TF.setNumRows(0);
            
            ArrayList<Aluno> alunos = alunoBanco.getLista();
            
            for (int i = 0; i < alunos.size(); i++) {                
                TF.addRow(new Object[]{
                    alunos.get(i).getNome(),
                    alunos.get(i).getCPF(),});
            }
        } catch (Exception ex) {
            Logger.getLogger(ViewFichaExercicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formAncestorAdded

    private void tableAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAlunoMouseClicked
        // Ao Clicar na Tabela

        int indice = tableAluno.getSelectedRow();

        String CPF = tableAluno.getValueAt(indice, 1).toString();
        System.out.println(CPF);

        try {
            if (indice >= 0 && CPF != null) {
                
                
               DefaultTableModel TF = (DefaultTableModel) tableExercicios.getModel();
                TF.setNumRows(0);

                for(Exercicio e : new ExercicioDAO().getExercicios(CPF)){                
                    TF.addRow(new Object[]{
                        e.getNome(),
                        e.getRepeticao(),
                        e.getEquipamento().getNome(),});                    
                }

            } else {

                JOptionPane.showMessageDialog(null, "Selecione o Aluno na Tabela!!!");
                indice = -1;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
    }//GEN-LAST:event_tableAlunoMouseClicked

    private void PesquisarAlunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarAlunActionPerformed
        try {
            
            DefaultTableModel TF = (DefaultTableModel) tableAluno.getModel();
            TF.setNumRows(0);
            
            ArrayList<Aluno> alunos = alunoBanco.getLista();
            
            for (int i = 0; i < alunos.size(); i++) {
                
                if (alunos.get(i).getCPF().contains(pesquisarAlun.getText()) || alunos.get(i).getNome().contains(pesquisarAlun.getText())) {
                    
                    TF.addRow(new Object[]{
                        alunos.get(i).getNome(),
                        alunos.get(i).getCPF(),});
                }
            }
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_PesquisarAlunActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Equipamentos;
    private javax.swing.JButton PesquisarAlun;
    private javax.swing.JScrollPane ScrollTabelaAlun;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Turmas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel painelTurmas;
    private javax.swing.JTextField pesquisarAlun;
    private javax.swing.JTable tableAluno;
    private javax.swing.JTable tableExercicios;
    // End of variables declaration//GEN-END:variables

}
