/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Visualizar;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

import objetos.Gastos;
import objetos_dao.GastosDAO;


/**
 *
 * @author Marco Antônio
 */
public class ViewGastoMensal extends javax.swing.JPanel {

    /**
     * Creates new form OpAlunoExerc
     */
    
    
    public ViewGastoMensal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        painelTurmas = new javax.swing.JPanel();
        Equipamentos = new javax.swing.JLabel();
        ScrollTabelaAgenServ = new javax.swing.JScrollPane();
        TabelaGasto = new javax.swing.JTable();
        spinnerAno = new javax.swing.JSpinner();
        Equipamentos1 = new javax.swing.JLabel();
        Equipamentos2 = new javax.swing.JLabel();
        comboMes = new javax.swing.JComboBox<>();
        PesquisarAgenGast = new javax.swing.JButton();
        Equipamentos3 = new javax.swing.JLabel();
        totalValor = new javax.swing.JLabel();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        Titulo.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Gastos");

        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        Equipamentos.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Equipamentos.setText("Gastos");

        TabelaGasto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabelaGasto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TabelaGasto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Descrição", "Data", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaGasto.setToolTipText("");
        TabelaGasto.setAlignmentX(1.0F);
        TabelaGasto.setAlignmentY(1.0F);
        TabelaGasto.setRowHeight(28);
        ScrollTabelaAgenServ.setViewportView(TabelaGasto);

        spinnerAno.setModel(new javax.swing.SpinnerNumberModel(2019, 2019, 2020, 1));

        Equipamentos1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Equipamentos1.setText("Mês:");

        Equipamentos2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Equipamentos2.setText("Ano:");

        comboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        PesquisarAgenGast.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        PesquisarAgenGast.setText("Procurar");
        PesquisarAgenGast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarAgenGastActionPerformed(evt);
            }
        });

        Equipamentos3.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Equipamentos3.setText("Total:");

        totalValor.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N

        javax.swing.GroupLayout painelTurmasLayout = new javax.swing.GroupLayout(painelTurmas);
        painelTurmas.setLayout(painelTurmasLayout);
        painelTurmasLayout.setHorizontalGroup(
            painelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTurmasLayout.createSequentialGroup()
                .addGap(545, 545, 545)
                .addComponent(Equipamentos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTurmasLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(painelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelTurmasLayout.createSequentialGroup()
                        .addGroup(painelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelTurmasLayout.createSequentialGroup()
                                .addComponent(Equipamentos1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboMes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(painelTurmasLayout.createSequentialGroup()
                                .addComponent(Equipamentos2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spinnerAno, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 62, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(painelTurmasLayout.createSequentialGroup()
                        .addComponent(PesquisarAgenGast)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(ScrollTabelaAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTurmasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Equipamentos3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalValor, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        painelTurmasLayout.setVerticalGroup(
            painelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelTurmasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Equipamentos)
                .addGroup(painelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelTurmasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ScrollTabelaAgenServ, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(painelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalValor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Equipamentos3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelTurmasLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(painelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Equipamentos1)
                            .addComponent(comboMes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(spinnerAno, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Equipamentos2))
                        .addGap(32, 32, 32)
                        .addComponent(PesquisarAgenGast)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Visualizar", painelTurmas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        
    }//GEN-LAST:event_formAncestorAdded

    private void PesquisarAgenGastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarAgenGastActionPerformed
        
        try {
            ArrayList<Gastos> gastos;
            float total = 0;
            
            if(comboMes.getSelectedIndex() == 0)
                gastos = new GastosDAO().getGastos(Integer.valueOf(spinnerAno.getValue().toString()));
            else
                gastos = new GastosDAO().getGastos(comboMes.getSelectedIndex(), Integer.valueOf(spinnerAno.getValue().toString()));
            
            DefaultTableModel TF = (DefaultTableModel) TabelaGasto.getModel();
            TF.setNumRows(0);
            
            for (Gastos g : gastos) {
                total += g.getValor();
                TF.addRow(new Object[]{
                    g.getDescricao(),
                    new SimpleDateFormat("dd/MM/yyyy").format(g.getData()),
                    "R$ " + String.format("%.2f", g.getValor()),});
            }
            
            totalValor.setText("R$ " + total);
            
        } catch (Exception ex) {
            Logger.getLogger(ViewGastoMensal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_PesquisarAgenGastActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Equipamentos;
    private javax.swing.JLabel Equipamentos1;
    private javax.swing.JLabel Equipamentos2;
    private javax.swing.JLabel Equipamentos3;
    private javax.swing.JButton PesquisarAgenGast;
    private javax.swing.JScrollPane ScrollTabelaAgenServ;
    private javax.swing.JTable TabelaGasto;
    private javax.swing.JLabel Titulo;
    private javax.swing.JComboBox<String> comboMes;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel painelTurmas;
    private javax.swing.JSpinner spinnerAno;
    private javax.swing.JLabel totalValor;
    // End of variables declaration//GEN-END:variables

}
