/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Administrador.AdmTurmas;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetos.Aluno;
import objetos.Instrutor;
import objetos.Turma;
import objetos.Turma_Aluno;
import objetos_dao.AlunoDAO;
import objetos_dao.InstrutorDAO;
import objetos_dao.TurmaDAO;
import objetos_dao.Turma_AlunoDAO;

/**
 *
 * @author GabrielFelipe
 */
public class OpTurma extends javax.swing.JPanel {

    TurmaDAO turmaBanco = new TurmaDAO();
    AlunoDAO alunoBanco = new AlunoDAO();
    InstrutorDAO instrutorBanco = new InstrutorDAO();
    
    Turma tempTurma;
    Aluno tempAluno;

    /**
     * Creates new form OpTurma1
     */
    public OpTurma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaFunc = new javax.swing.JTabbedPane();
        AbaTurma = new javax.swing.JPanel();
        IDTurma = new javax.swing.JLabel();
        idTurma = new javax.swing.JLabel();
        InstrTurma = new javax.swing.JLabel();
        instrTurma = new javax.swing.JLabel();
        PesquisarAlunTurma = new javax.swing.JButton();
        pesquisarAlunTurma = new javax.swing.JTextField();
        ScrollTabelaAlunTurma = new javax.swing.JScrollPane();
        TabelaAlunTurma = new javax.swing.JTable();
        PainelHorarios = new javax.swing.JPanel();
        TituloHorarios = new javax.swing.JLabel();
        SegTurma = new javax.swing.JLabel();
        segTurma = new javax.swing.JComboBox<>();
        TerTurma = new javax.swing.JLabel();
        terTurma = new javax.swing.JComboBox<>();
        QuaTurma = new javax.swing.JLabel();
        quaTurma = new javax.swing.JComboBox<>();
        QuinTurma = new javax.swing.JLabel();
        quinTurma = new javax.swing.JComboBox<>();
        SexTurma = new javax.swing.JLabel();
        sexTurma = new javax.swing.JComboBox<>();
        IDTurma1 = new javax.swing.JLabel();
        qtdMaxTurma = new javax.swing.JLabel();
        AbaCadTurma = new javax.swing.JPanel();
        InstrCadTurma = new javax.swing.JLabel();
        instrCadTurma = new javax.swing.JComboBox<Instrutor>();
        CadastrarCadTurma = new javax.swing.JButton();
        EditarCadTurma = new javax.swing.JButton();
        ExcluirCadTurma = new javax.swing.JButton();
        PainelHoraCadTurma = new javax.swing.JPanel();
        TituloHoraCadTurma = new javax.swing.JLabel();
        SegCadTurma = new javax.swing.JLabel();
        segCadTurma = new javax.swing.JComboBox<>();
        TerCadTurma = new javax.swing.JLabel();
        terCadTurma = new javax.swing.JComboBox<>();
        QuaCadTurma = new javax.swing.JLabel();
        quaCadTurma = new javax.swing.JComboBox<>();
        QuinCadTurma = new javax.swing.JLabel();
        quinCadTurma = new javax.swing.JComboBox<>();
        SexCadTurma = new javax.swing.JLabel();
        sexCadTurma = new javax.swing.JComboBox<>();
        qtdMaxTurmaCtrl = new javax.swing.JSpinner();
        InstrQtdMax = new javax.swing.JLabel();
        AbaCadAlunTurma = new javax.swing.JPanel();
        PesquisarCadAlunTurma = new javax.swing.JButton();
        pesquisarCadAlunTurma = new javax.swing.JTextField();
        CadastrarAlunTurma = new javax.swing.JButton();
        ExcluirAlunTurma = new javax.swing.JButton();
        ScrollTabelaCadAlunTurma1 = new javax.swing.JScrollPane();
        TabelaCadAlunTurma1 = new javax.swing.JTable();
        ScrollTabelaCadAlunTurma2 = new javax.swing.JScrollPane();
        TabelaCadAlunTurma2 = new javax.swing.JTable();
        TabelaPesquisaTurma = new javax.swing.JPanel();
        PesquisarTurma = new javax.swing.JButton();
        pesquisarTurma = new javax.swing.JTextField();
        ScrollTabelaTurma = new javax.swing.JScrollPane();
        TabelaTurma = new javax.swing.JTable();
        LimparTurma = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        TelaFunc.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        AbaTurma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        IDTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        IDTurma.setText("ID:");

        idTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        idTurma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        InstrTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        InstrTurma.setText("Instrutor:");

        instrTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        instrTurma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        PesquisarAlunTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        PesquisarAlunTurma.setText("Pesquisar Aluno");
        PesquisarAlunTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarAlunTurmaActionPerformed(evt);
            }
        });

        pesquisarAlunTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pesquisarAlunTurma.setPreferredSize(new java.awt.Dimension(74, 32));

        TabelaAlunTurma.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabelaAlunTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TabelaAlunTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaAlunTurma.setToolTipText("");
        TabelaAlunTurma.setAlignmentX(1.0F);
        TabelaAlunTurma.setAlignmentY(1.0F);
        TabelaAlunTurma.setEnabled(false);
        TabelaAlunTurma.setRowHeight(28);
        ScrollTabelaAlunTurma.setViewportView(TabelaAlunTurma);

        PainelHorarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TituloHorarios.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        TituloHorarios.setText("Horários semanais");

        SegTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SegTurma.setText("Segunda-Feira:");

        segTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        segTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "8h00 às 10h00", "10h00 às 12h00", "13h00 às 15h00", "15h00 às 17h00", "18h00 às 20h00", "20h00 às 22h00" }));
        segTurma.setEnabled(false);

        TerTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TerTurma.setText("Terça-Feira:");

        terTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        terTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "8h00 às 10h00", "10h00 às 12h00", "13h00 às 15h00", "15h00 às 17h00", "18h00 às 20h00", "20h00 às 22h00" }));
        terTurma.setEnabled(false);

        QuaTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        QuaTurma.setText("Quarta-Feira:");

        quaTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quaTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "8h00 às 10h00", "10h00 às 12h00", "13h00 às 15h00", "15h00 às 17h00", "18h00 às 20h00", "20h00 às 22h00" }));
        quaTurma.setEnabled(false);

        QuinTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        QuinTurma.setText("Quinta-Feira:");

        quinTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quinTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "8h00 às 10h00", "10h00 às 12h00", "13h00 às 15h00", "15h00 às 17h00", "18h00 às 20h00", "20h00 às 22h00" }));
        quinTurma.setEnabled(false);

        SexTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SexTurma.setText("Sexta-Feira:");

        sexTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sexTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "8h00 às 10h00", "10h00 às 12h00", "13h00 às 15h00", "15h00 às 17h00", "18h00 às 20h00", "20h00 às 22h00" }));
        sexTurma.setEnabled(false);

        javax.swing.GroupLayout PainelHorariosLayout = new javax.swing.GroupLayout(PainelHorarios);
        PainelHorarios.setLayout(PainelHorariosLayout);
        PainelHorariosLayout.setHorizontalGroup(
            PainelHorariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelHorariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelHorariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelHorariosLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(TituloHorarios))
                    .addGroup(PainelHorariosLayout.createSequentialGroup()
                        .addGroup(PainelHorariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SexTurma)
                            .addComponent(QuinTurma)
                            .addComponent(SegTurma)
                            .addComponent(TerTurma)
                            .addComponent(QuaTurma))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelHorariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(segTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(terTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quinTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quaTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelHorariosLayout.setVerticalGroup(
            PainelHorariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelHorariosLayout.createSequentialGroup()
                .addComponent(TituloHorarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelHorariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SegTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(segTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PainelHorariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TerTurma)
                    .addComponent(terTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(PainelHorariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuaTurma)
                    .addComponent(quaTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PainelHorariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuinTurma)
                    .addComponent(quinTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(PainelHorariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SexTurma)))
        );

        IDTurma1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        IDTurma1.setText("Quantidade máxima:");

        qtdMaxTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        qtdMaxTurma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout AbaTurmaLayout = new javax.swing.GroupLayout(AbaTurma);
        AbaTurma.setLayout(AbaTurmaLayout);
        AbaTurmaLayout.setHorizontalGroup(
            AbaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaTurmaLayout.createSequentialGroup()
                .addGroup(AbaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AbaTurmaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(AbaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(idTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaTurmaLayout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addComponent(IDTurma)
                                    .addGap(66, 66, 66))))
                        .addGroup(AbaTurmaLayout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(InstrTurma))
                        .addGroup(AbaTurmaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(instrTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaTurmaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(qtdMaxTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AbaTurmaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IDTurma1)))
                .addGap(10, 10, 10)
                .addComponent(PainelHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AbaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollTabelaAlunTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AbaTurmaLayout.createSequentialGroup()
                        .addComponent(PesquisarAlunTurma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisarAlunTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        AbaTurmaLayout.setVerticalGroup(
            AbaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaTurmaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AbaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaTurmaLayout.createSequentialGroup()
                        .addComponent(ScrollTabelaAlunTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AbaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PesquisarAlunTurma)
                            .addComponent(pesquisarAlunTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(PainelHorarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(AbaTurmaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(IDTurma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InstrTurma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instrTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IDTurma1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qtdMaxTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TelaFunc.addTab("Turmas", AbaTurma);

        AbaCadTurma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        InstrCadTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        InstrCadTurma.setText("Instrutor:");

        instrCadTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        instrCadTurma.setActionCommand("");

        CadastrarCadTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CadastrarCadTurma.setText("Cadastrar");
        CadastrarCadTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarCadTurmaActionPerformed(evt);
            }
        });

        EditarCadTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        EditarCadTurma.setText("Editar");
        EditarCadTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarCadTurmaActionPerformed(evt);
            }
        });

        ExcluirCadTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ExcluirCadTurma.setText("Excluir");
        ExcluirCadTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirCadTurmaActionPerformed(evt);
            }
        });

        PainelHoraCadTurma.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TituloHoraCadTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        TituloHoraCadTurma.setText("Horários semanais");

        SegCadTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SegCadTurma.setText("Segunda-Feira:");

        segCadTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        segCadTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "8h00 às 10h00", "10h00 às 12h00", "13h00 às 15h00", "15h00 às 17h00", "18h00 às 20h00", "20h00 às 22h00" }));

        TerCadTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TerCadTurma.setText("Terça-Feira:");

        terCadTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        terCadTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "8h00 às 10h00", "10h00 às 12h00", "13h00 às 15h00", "15h00 às 17h00", "18h00 às 20h00", "20h00 às 22h00" }));

        QuaCadTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        QuaCadTurma.setText("Quarta-Feira:");

        quaCadTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quaCadTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "8h00 às 10h00", "10h00 às 12h00", "13h00 às 15h00", "15h00 às 17h00", "18h00 às 20h00", "20h00 às 22h00" }));

        QuinCadTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        QuinCadTurma.setText("Quinta-Feira:");

        quinCadTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quinCadTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "8h00 às 10h00", "10h00 às 12h00", "13h00 às 15h00", "15h00 às 17h00", "18h00 às 20h00", "20h00 às 22h00" }));

        SexCadTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SexCadTurma.setText("Sexta-Feira:");

        sexCadTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sexCadTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "8h00 às 10h00", "10h00 às 12h00", "13h00 às 15h00", "15h00 às 17h00", "18h00 às 20h00", "20h00 às 22h00" }));

        javax.swing.GroupLayout PainelHoraCadTurmaLayout = new javax.swing.GroupLayout(PainelHoraCadTurma);
        PainelHoraCadTurma.setLayout(PainelHoraCadTurmaLayout);
        PainelHoraCadTurmaLayout.setHorizontalGroup(
            PainelHoraCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelHoraCadTurmaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelHoraCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelHoraCadTurmaLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(TituloHoraCadTurma))
                    .addGroup(PainelHoraCadTurmaLayout.createSequentialGroup()
                        .addGroup(PainelHoraCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SexCadTurma)
                            .addComponent(QuinCadTurma)
                            .addComponent(SegCadTurma)
                            .addComponent(TerCadTurma)
                            .addComponent(QuaCadTurma))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelHoraCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(segCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(terCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quinCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quaCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        PainelHoraCadTurmaLayout.setVerticalGroup(
            PainelHoraCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelHoraCadTurmaLayout.createSequentialGroup()
                .addComponent(TituloHoraCadTurma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelHoraCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SegCadTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(segCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PainelHoraCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TerCadTurma)
                    .addComponent(terCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(PainelHoraCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuaCadTurma)
                    .addComponent(quaCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PainelHoraCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuinCadTurma)
                    .addComponent(quinCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(PainelHoraCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SexCadTurma)))
        );

        qtdMaxTurmaCtrl.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        InstrQtdMax.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        InstrQtdMax.setText("Quantidade máxima:");

        javax.swing.GroupLayout AbaCadTurmaLayout = new javax.swing.GroupLayout(AbaCadTurma);
        AbaCadTurma.setLayout(AbaCadTurmaLayout);
        AbaCadTurmaLayout.setHorizontalGroup(
            AbaCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaCadTurmaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(AbaCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaCadTurmaLayout.createSequentialGroup()
                        .addComponent(InstrQtdMax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(qtdMaxTurmaCtrl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AbaCadTurmaLayout.createSequentialGroup()
                        .addComponent(InstrCadTurma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(instrCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(PainelHoraCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(AbaCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExcluirCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CadastrarCadTurma)
                    .addComponent(EditarCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );
        AbaCadTurmaLayout.setVerticalGroup(
            AbaCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCadTurmaLayout.createSequentialGroup()
                .addGroup(AbaCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaCadTurmaLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(CadastrarCadTurma)
                        .addGap(18, 18, 18)
                        .addComponent(EditarCadTurma)
                        .addGap(18, 18, 18)
                        .addComponent(ExcluirCadTurma)
                        .addGap(0, 68, Short.MAX_VALUE))
                    .addComponent(PainelHoraCadTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(AbaCadTurmaLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(AbaCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InstrCadTurma)
                    .addComponent(instrCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AbaCadTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(InstrQtdMax)
                    .addComponent(qtdMaxTurmaCtrl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TelaFunc.addTab("Controle", AbaCadTurma);

        AbaCadAlunTurma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PesquisarCadAlunTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        PesquisarCadAlunTurma.setText("Pesquisar Aluno");
        PesquisarCadAlunTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarCadAlunTurmaActionPerformed(evt);
            }
        });

        pesquisarCadAlunTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pesquisarCadAlunTurma.setPreferredSize(new java.awt.Dimension(74, 32));

        CadastrarAlunTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CadastrarAlunTurma.setText("Cadastrar");
        CadastrarAlunTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarAlunTurmaActionPerformed(evt);
            }
        });

        ExcluirAlunTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ExcluirAlunTurma.setText("Excluir");
        ExcluirAlunTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirAlunTurmaActionPerformed(evt);
            }
        });

        TabelaCadAlunTurma1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabelaCadAlunTurma1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TabelaCadAlunTurma1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaCadAlunTurma1.setToolTipText("");
        TabelaCadAlunTurma1.setAlignmentX(1.0F);
        TabelaCadAlunTurma1.setAlignmentY(1.0F);
        TabelaCadAlunTurma1.setRowHeight(28);
        TabelaCadAlunTurma1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaCadAlunTurma1MouseClicked(evt);
            }
        });
        ScrollTabelaCadAlunTurma1.setViewportView(TabelaCadAlunTurma1);

        TabelaCadAlunTurma2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabelaCadAlunTurma2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TabelaCadAlunTurma2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaCadAlunTurma2.setToolTipText("");
        TabelaCadAlunTurma2.setAlignmentX(1.0F);
        TabelaCadAlunTurma2.setAlignmentY(1.0F);
        TabelaCadAlunTurma2.setRowHeight(28);
        ScrollTabelaCadAlunTurma2.setViewportView(TabelaCadAlunTurma2);

        javax.swing.GroupLayout AbaCadAlunTurmaLayout = new javax.swing.GroupLayout(AbaCadAlunTurma);
        AbaCadAlunTurma.setLayout(AbaCadAlunTurmaLayout);
        AbaCadAlunTurmaLayout.setHorizontalGroup(
            AbaCadAlunTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCadAlunTurmaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AbaCadAlunTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollTabelaCadAlunTurma1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AbaCadAlunTurmaLayout.createSequentialGroup()
                        .addComponent(PesquisarCadAlunTurma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisarCadAlunTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(AbaCadAlunTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaCadAlunTurmaLayout.createSequentialGroup()
                        .addComponent(ScrollTabelaCadAlunTurma2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaCadAlunTurmaLayout.createSequentialGroup()
                        .addComponent(CadastrarAlunTurma)
                        .addGap(38, 38, 38)
                        .addComponent(ExcluirAlunTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))))
        );
        AbaCadAlunTurmaLayout.setVerticalGroup(
            AbaCadAlunTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCadAlunTurmaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AbaCadAlunTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollTabelaCadAlunTurma1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScrollTabelaCadAlunTurma2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AbaCadAlunTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PesquisarCadAlunTurma)
                    .addComponent(pesquisarCadAlunTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CadastrarAlunTurma)
                    .addComponent(ExcluirAlunTurma))
                .addContainerGap())
        );

        TelaFunc.addTab("Alunos", AbaCadAlunTurma);

        TabelaPesquisaTurma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PesquisarTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        PesquisarTurma.setText("Pesquisar");
        PesquisarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarTurmaActionPerformed(evt);
            }
        });

        pesquisarTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pesquisarTurma.setPreferredSize(new java.awt.Dimension(74, 32));

        TabelaTurma.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabelaTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TabelaTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Instrutor", "Quantidade de alunos", "Quantidade máxima"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaTurma.setToolTipText("");
        TabelaTurma.setAlignmentX(1.0F);
        TabelaTurma.setAlignmentY(1.0F);
        TabelaTurma.setRowHeight(28);
        TabelaTurma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaTurmaMouseClicked(evt);
            }
        });
        ScrollTabelaTurma.setViewportView(TabelaTurma);

        LimparTurma.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        LimparTurma.setText("Limpar");
        LimparTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparTurmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TabelaPesquisaTurmaLayout = new javax.swing.GroupLayout(TabelaPesquisaTurma);
        TabelaPesquisaTurma.setLayout(TabelaPesquisaTurmaLayout);
        TabelaPesquisaTurmaLayout.setHorizontalGroup(
            TabelaPesquisaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelaPesquisaTurmaLayout.createSequentialGroup()
                .addGroup(TabelaPesquisaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TabelaPesquisaTurmaLayout.createSequentialGroup()
                        .addComponent(PesquisarTurma)
                        .addGap(18, 18, 18)
                        .addComponent(pesquisarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LimparTurma))
                    .addGroup(TabelaPesquisaTurmaLayout.createSequentialGroup()
                        .addComponent(ScrollTabelaTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        TabelaPesquisaTurmaLayout.setVerticalGroup(
            TabelaPesquisaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelaPesquisaTurmaLayout.createSequentialGroup()
                .addGroup(TabelaPesquisaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TabelaPesquisaTurmaLayout.createSequentialGroup()
                        .addComponent(LimparTurma)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabelaPesquisaTurmaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(TabelaPesquisaTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PesquisarTurma)
                            .addComponent(pesquisarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(ScrollTabelaTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Titulo.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Gerenciar turmas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TelaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TabelaPesquisaTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TelaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(TabelaPesquisaTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PesquisarAlunTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarAlunTurmaActionPerformed
        try {
            // Botão Pesquisa Aluno da Turma
            AtualizaAlunTurma(tempTurma, TabelaAlunTurma);
            
            DefaultTableModel TF = (DefaultTableModel) TabelaAlunTurma.getModel();
            DefaultTableModel novoModel =   new javax.swing.table.DefaultTableModel(
                                            new Object [][] {},
                                            new String [] {
                                                "Nome", "CPF"
                                            });
            
            for (int i = 0; i < TF.getRowCount(); i++) {                
                if (TF.getValueAt(i, 0).toString().contains(pesquisarAlunTurma.getText()) || TF.getValueAt(i, 1).toString().contains(pesquisarAlunTurma.getText())) {
                    novoModel.addRow(new Object[]{TF.getValueAt(i, 0), TF.getValueAt(i, 1)}); 
                }
            }
            
            TabelaAlunTurma.setModel(novoModel);
        } catch (Exception ex) {
            Logger.getLogger(OpTurma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PesquisarAlunTurmaActionPerformed

    private void CadastrarCadTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarCadTurmaActionPerformed
        // Botão Cadastrar

        try {
            if( instrCadTurma.getSelectedItem() == null ||
                Integer.parseInt(qtdMaxTurmaCtrl.getValue().toString()) == 0 ||
                   (segCadTurma.getSelectedItem().toString().equals("Nenhum") &&
                    terCadTurma.getSelectedItem().toString().equals("Nenhum") &&
                    quaCadTurma.getSelectedItem().toString().equals("Nenhum") &&
                    quinCadTurma.getSelectedItem().toString().equals("Nenhum") &&
                    sexCadTurma.getSelectedItem().toString().equals("Nenhum")))
                throw new Exception("Preencha todos os dados");            
            
            
            
            tempTurma = new Turma();
            
            tempTurma.setInstrutor(new InstrutorDAO().getInstrutor(((Instrutor)instrCadTurma.getSelectedItem()).getCPF()));
            tempTurma.setQuantidade(Integer.parseInt(qtdMaxTurmaCtrl.getValue().toString()));
            tempTurma.setHorario((String) segCadTurma.getSelectedItem() + "|"
                    + (String) terCadTurma.getSelectedItem() + "|"
                    + (String) quaCadTurma.getSelectedItem() + "|"
                    + (String) quinCadTurma.getSelectedItem() + "|"
                    + (String) sexCadTurma.getSelectedItem());  

            for(Turma t : turmaBanco.getTurmasInstrutor(tempTurma.getInstrutor().getCPF())){
                if( (!(t.getHorario().split("\\|")[0].equals("Nenhum")) && t.getHorario().split("\\|")[0].equals(tempTurma.getHorario().split("\\|")[0])) ||
                    (!(t.getHorario().split("\\|")[1].equals("Nenhum")) && t.getHorario().split("\\|")[1].equals(tempTurma.getHorario().split("\\|")[1])) ||
                    (!(t.getHorario().split("\\|")[2].equals("Nenhum")) && t.getHorario().split("\\|")[2].equals(tempTurma.getHorario().split("\\|")[2])) ||    
                    (!(t.getHorario().split("\\|")[3].equals("Nenhum")) && t.getHorario().split("\\|")[3].equals(tempTurma.getHorario().split("\\|")[3])) ||    
                    (!(t.getHorario().split("\\|")[4].equals("Nenhum")) && t.getHorario().split("\\|")[4].equals(tempTurma.getHorario().split("\\|")[4])))
                    throw new Exception("O Instrutor não pode ser alocado para esses horários");
            }     

            turmaBanco.adiciona(tempTurma);
            JOptionPane.showMessageDialog(null, "Turma cadastrada com sucesso");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
//            Logger.getLogger(OpTurma.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_CadastrarCadTurmaActionPerformed

    private void CadastrarAlunTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarAlunTurmaActionPerformed
        // Cadastrar Aluno na Turma
        try {                  
            
            int indice = TabelaCadAlunTurma1.getSelectedRow();
            
            if(tempTurma.getQuantidade() <= new Turma_AlunoDAO().qtdAlunos(tempTurma.getId()))
                throw new Exception("A turma atingiu o limite de alunos");
        
            if (indice >= 0 && tempTurma != null) {
                
                new Turma_AlunoDAO().adiciona(new Turma_Aluno(new AlunoDAO().getAluno((String)TabelaCadAlunTurma1.getValueAt(indice, 1)), tempTurma));
                AtualizaAlunTurma(tempTurma, TabelaCadAlunTurma2);

            } else {
                JOptionPane.showMessageDialog(null, "Selecione uma turma na tabela");
            }

        } catch (Exception e ) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_CadastrarAlunTurmaActionPerformed

    private void TabelaTurmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaTurmaMouseClicked
        // Quando Clica comMouse na Tabela
        
        try {
            int id = (int)TabelaTurma.getValueAt(TabelaTurma.getSelectedRow(), 0); 
            tempTurma = turmaBanco.getTurma(id);
            
            if (id >= 0 && tempTurma != null) {
                
                //Turma
                idTurma.setText(String.valueOf(tempTurma.getId()));
                instrTurma.setText(tempTurma.getInstrutor().getNome());
                qtdMaxTurma.setText(String.valueOf(tempTurma.getQuantidade()));
                segTurma.setSelectedItem(tempTurma.getHorario().split("\\|")[0]);
                terTurma.setSelectedItem(tempTurma.getHorario().split("\\|")[1]);
                quaTurma.setSelectedItem(tempTurma.getHorario().split("\\|")[2]);
                quinTurma.setSelectedItem(tempTurma.getHorario().split("\\|")[3]);
                sexTurma.setSelectedItem(tempTurma.getHorario().split("\\|")[4]);

                AtualizaAlunTurma(tempTurma, TabelaAlunTurma);
                AtualizaAlunoExterno(tempTurma);

                //Controle
                instrCadTurma.setSelectedItem(tempTurma.getInstrutor());
                qtdMaxTurmaCtrl.setValue(tempTurma.getQuantidade());
                segCadTurma.setSelectedItem((tempTurma).getHorario().split("\\|")[0]);
                terCadTurma.setSelectedItem(tempTurma.getHorario().split("\\|")[1]);
                quaCadTurma.setSelectedItem(tempTurma.getHorario().split("\\|")[2]);
                quinCadTurma.setSelectedItem(tempTurma.getHorario().split("\\|")[3]);
                sexCadTurma.setSelectedItem(tempTurma.getHorario().split("\\|")[4]);

                //Alunos
                
                PesquisarAlunTurma.setEnabled(true);
                
                CadastrarCadTurma.setEnabled(false);
                EditarCadTurma.setEnabled(true);
                ExcluirCadTurma.setEnabled(true);                
                
                PesquisarCadAlunTurma.setEnabled(true);
                ExcluirAlunTurma.setEnabled(true);
                CadastrarAlunTurma.setEnabled(true);                
                
                AtualizaAlunTurma(tempTurma, TabelaCadAlunTurma2);

            } else {
                JOptionPane.showMessageDialog(null, "Selecione uma turma na tabela");
                tempTurma = null;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione uma turma válida");
            tempTurma = null;
        }
    }//GEN-LAST:event_TabelaTurmaMouseClicked

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        try {
            // Quando a Janela Abre
            
            instrCadTurma.addItem(null);
             
            for(Instrutor i : instrutorBanco.getLista()){
                instrCadTurma.addItem(i);
            }
            
            PesquisarAlunTurma.setEnabled(false);
                
            CadastrarCadTurma.setEnabled(true);
            EditarCadTurma.setEnabled(false);
            ExcluirCadTurma.setEnabled(false);                

            PesquisarCadAlunTurma.setEnabled(false);
            ExcluirAlunTurma.setEnabled(false);
            CadastrarAlunTurma.setEnabled(false);     
            
            AtualizaTabela();
        } catch (Exception ex) {
            Logger.getLogger(OpTurma.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_formAncestorAdded

    private void EditarCadTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarCadTurmaActionPerformed
        // Botão Editar

        try {            
            Turma tempTurma2 = new Turma();
            
            if(tempTurma == null)
                throw new Exception("Selecione uma turma na tabela");
                
            tempTurma2.setInstrutor(new InstrutorDAO().getInstrutor(((Instrutor)instrCadTurma.getSelectedItem()).getCPF()));
            tempTurma2.setQuantidade(Integer.parseInt(qtdMaxTurmaCtrl.getValue().toString()));
            tempTurma2.setHorario((String) segCadTurma.getSelectedItem() + "|"
                    + (String) terCadTurma.getSelectedItem() + "|"
                    + (String) quaCadTurma.getSelectedItem() + "|"
                    + (String) quinCadTurma.getSelectedItem() + "|"
                    + (String) sexCadTurma.getSelectedItem());
            

            for(Turma t : turmaBanco.getTurmasInstrutor(tempTurma2.getInstrutor().getCPF())){
                if(t.getId() != tempTurma.getId()){
                    if( (!(t.getHorario().split("\\|")[0].equals("Nenhum")) && t.getHorario().split("\\|")[0].equals(tempTurma2.getHorario().split("\\|")[0])) ||
                        (!(t.getHorario().split("\\|")[1].equals("Nenhum")) && t.getHorario().split("\\|")[1].equals(tempTurma2.getHorario().split("\\|")[1])) ||
                        (!(t.getHorario().split("\\|")[2].equals("Nenhum")) && t.getHorario().split("\\|")[2].equals(tempTurma2.getHorario().split("\\|")[2])) ||    
                        (!(t.getHorario().split("\\|")[3].equals("Nenhum")) && t.getHorario().split("\\|")[3].equals(tempTurma2.getHorario().split("\\|")[3])) ||    
                        (!(t.getHorario().split("\\|")[4].equals("Nenhum")) && t.getHorario().split("\\|")[4].equals(tempTurma2.getHorario().split("\\|")[4])))
                        throw new Exception("O Instrutor não pode ser alocado para esses horários");
                }
            }

            tempTurma2.setId((int) TabelaTurma.getValueAt(TabelaTurma.getSelectedRow(), 0));

            EditTurmaAlerta ETA = new EditTurmaAlerta(tempTurma, tempTurma2, this);
            ETA.setVisible(true);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_EditarCadTurmaActionPerformed

    private void ExcluirCadTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirCadTurmaActionPerformed
        try {

            if (tempTurma == null) 
                throw new Exception("Selecione uma turma válida na tabela");
                
            ExcTurmaAlerta ETA = new ExcTurmaAlerta(tempTurma, this);
            ETA.setVisible(true);
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_ExcluirCadTurmaActionPerformed

    private void LimparTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparTurmaActionPerformed
        Limpar();
    }//GEN-LAST:event_LimparTurmaActionPerformed

    private void ExcluirAlunTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirAlunTurmaActionPerformed
        // Excluir Aluno na Turma  
        try {
            if(tempAluno == null)
                throw new Exception("Selecione um aluno da lista");            

            new Turma_AlunoDAO().remove(new Turma_Aluno(tempAluno, tempTurma));
            AtualizaAlunTurma(tempTurma, TabelaCadAlunTurma2);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_ExcluirAlunTurmaActionPerformed

    private void PesquisarCadAlunTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarCadAlunTurmaActionPerformed
           
        try {
            AtualizaAlunoExterno(tempTurma);  
            
            DefaultTableModel TF = (DefaultTableModel) TabelaCadAlunTurma1.getModel();
            DefaultTableModel novoModel =   new javax.swing.table.DefaultTableModel(
                                            new Object [][] {},
                                            new String [] {
                                                "Nome", "CPF"
                                            });
            
            for (int i = 0; i < TF.getRowCount(); i++) {                
                if (TF.getValueAt(i, 0).toString().contains(pesquisarCadAlunTurma.getText()) || TF.getValueAt(i, 1).toString().contains(pesquisarCadAlunTurma.getText())) {
                    novoModel.addRow(new Object[]{TF.getValueAt(i, 0), TF.getValueAt(i, 1)}); 
                }
            }
            
            TabelaCadAlunTurma1.setModel(novoModel);
        } catch (Exception ex) {
            Logger.getLogger(OpTurma.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_PesquisarCadAlunTurmaActionPerformed

    private void PesquisarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarTurmaActionPerformed
        try {
            // Botão Pesquisar Turma

            DefaultTableModel TF = (DefaultTableModel) TabelaTurma.getModel();
            TF.setNumRows(0);
            
            int idTurma = Integer.valueOf(pesquisarTurma.getText());
            Turma turma = turmaBanco.getTurma(idTurma);            
            
            if(turma != null){
                if (turma.getId() == Integer.parseInt(pesquisarTurma.getText())) {
                    TF.setNumRows(0);

                    TF.addRow(new Object[]{
                        turma.getId(),
                        turma.getInstrutor().getNome(),
                        turma.getAlunos().size(),
                        turma.getQuantidade(),});
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Parâmetro de pesquisa inválido");
        }
    }//GEN-LAST:event_PesquisarTurmaActionPerformed

    private void TabelaCadAlunTurma1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaCadAlunTurma1MouseClicked
        try {
            tempAluno =  alunoBanco.getAluno((String) TabelaCadAlunTurma1.getValueAt(TabelaCadAlunTurma1.getSelectedRow(), 1));
        } catch (Exception ex) {
            Logger.getLogger(OpTurma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TabelaCadAlunTurma1MouseClicked

    public void AtualizaTabela() {

        try {
            DefaultTableModel TF = (DefaultTableModel) TabelaTurma.getModel();
            TF.setNumRows(0);
            
            ArrayList<Turma> turmas = turmaBanco.getLista();
            
            for (Turma t : turmas) {                
                TF.addRow(new Object[]{
                    t.getId(),
                    t.getInstrutor().getNome(),
                    t.getAlunos().size(),
                    t.getQuantidade(),});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    public void AtualizaAlunTurma(Turma turma, javax.swing.JTable tabela) {

        try {
            DefaultTableModel TF = (DefaultTableModel) tabela.getModel();
            TF.setNumRows(0);
            
            ArrayList<Aluno> alunos = turma.getAlunos();
            
            for (int i = 0; i < alunos.size(); i++) {
                
                TF.addRow(new Object[]{
                    alunos.get(i).getNome(),
                    alunos.get(i).getCPF(),});
            }
        } catch (Exception ex) {
            Logger.getLogger(OpTurma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void AtualizaAlun(javax.swing.JTable tabela) {

        try {
            DefaultTableModel TF = (DefaultTableModel) tabela.getModel();
            TF.setNumRows(0);
            
            ArrayList<Aluno> alunos = alunoBanco.getLista();
            
            for (int i = 0; i < alunos.size(); i++) {
                
                TF.addRow(new Object[]{
                    alunos.get(i).getNome(),
                    alunos.get(i).getCPF(),});
            }
        } catch (Exception ex) {
            Logger.getLogger(OpTurma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void AtualizaAlunoExterno(Turma t){
        try {
            DefaultTableModel TF = (DefaultTableModel) TabelaCadAlunTurma1.getModel();
            TF.setNumRows(0);
            
            ArrayList<Aluno> alunos = new Turma_AlunoDAO().getAlunosExternos(t.getId());
            
            for (Aluno a : alunos) {                
                TF.addRow(new Object[]{
                    a.getNome(),
                    a.getCPF(),});
            }
        } catch (Exception ex) {
            Logger.getLogger(OpTurma.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }

    public void Limpar() {

        //Turmas
        idTurma.setText(" ");
        instrTurma.setText(" ");
        segTurma.setSelectedIndex(0);
        terTurma.setSelectedIndex(0);
        quaTurma.setSelectedIndex(0);
        quinTurma.setSelectedIndex(0);
        sexTurma.setSelectedIndex(0);        
        qtdMaxTurma.setText("");
        
        ((DefaultTableModel) TabelaAlunTurma.getModel()).setNumRows(0);
        
        AtualizaTabela();

        //Controle
        instrCadTurma.setSelectedItem(null);
        segCadTurma.setSelectedIndex(0);
        terCadTurma.setSelectedIndex(0);
        quaCadTurma.setSelectedIndex(0);
        quinCadTurma.setSelectedIndex(0);
        sexCadTurma.setSelectedIndex(0);        
        qtdMaxTurmaCtrl.setValue(0);

        //Alunos
        ((DefaultTableModel) TabelaCadAlunTurma1.getModel()).setNumRows(0);
        
        PesquisarAlunTurma.setEnabled(false);
                
        CadastrarCadTurma.setEnabled(true);
        EditarCadTurma.setEnabled(false);
        ExcluirCadTurma.setEnabled(false);                

        PesquisarCadAlunTurma.setEnabled(false);
        ExcluirAlunTurma.setEnabled(false);
        CadastrarAlunTurma.setEnabled(false);
        
        tempTurma = null;
        
        ((DefaultTableModel) TabelaCadAlunTurma2.getModel()).setNumRows(0);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AbaCadAlunTurma;
    private javax.swing.JPanel AbaCadTurma;
    private javax.swing.JPanel AbaTurma;
    private javax.swing.JButton CadastrarAlunTurma;
    private javax.swing.JButton CadastrarCadTurma;
    private javax.swing.JButton EditarCadTurma;
    private javax.swing.JButton ExcluirAlunTurma;
    private javax.swing.JButton ExcluirCadTurma;
    private javax.swing.JLabel IDTurma;
    private javax.swing.JLabel IDTurma1;
    private javax.swing.JLabel InstrCadTurma;
    private javax.swing.JLabel InstrQtdMax;
    private javax.swing.JLabel InstrTurma;
    private javax.swing.JButton LimparTurma;
    private javax.swing.JPanel PainelHoraCadTurma;
    private javax.swing.JPanel PainelHorarios;
    private javax.swing.JButton PesquisarAlunTurma;
    private javax.swing.JButton PesquisarCadAlunTurma;
    private javax.swing.JButton PesquisarTurma;
    private javax.swing.JLabel QuaCadTurma;
    private javax.swing.JLabel QuaTurma;
    private javax.swing.JLabel QuinCadTurma;
    private javax.swing.JLabel QuinTurma;
    private javax.swing.JScrollPane ScrollTabelaAlunTurma;
    private javax.swing.JScrollPane ScrollTabelaCadAlunTurma1;
    private javax.swing.JScrollPane ScrollTabelaCadAlunTurma2;
    private javax.swing.JScrollPane ScrollTabelaTurma;
    private javax.swing.JLabel SegCadTurma;
    private javax.swing.JLabel SegTurma;
    private javax.swing.JLabel SexCadTurma;
    private javax.swing.JLabel SexTurma;
    private javax.swing.JTable TabelaAlunTurma;
    private javax.swing.JTable TabelaCadAlunTurma1;
    private javax.swing.JTable TabelaCadAlunTurma2;
    private javax.swing.JPanel TabelaPesquisaTurma;
    private javax.swing.JTable TabelaTurma;
    private javax.swing.JTabbedPane TelaFunc;
    private javax.swing.JLabel TerCadTurma;
    private javax.swing.JLabel TerTurma;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel TituloHoraCadTurma;
    private javax.swing.JLabel TituloHorarios;
    private javax.swing.JLabel idTurma;
    private javax.swing.JComboBox<Instrutor> instrCadTurma;
    private javax.swing.JLabel instrTurma;
    private javax.swing.JTextField pesquisarAlunTurma;
    private javax.swing.JTextField pesquisarCadAlunTurma;
    private javax.swing.JTextField pesquisarTurma;
    private javax.swing.JLabel qtdMaxTurma;
    private javax.swing.JSpinner qtdMaxTurmaCtrl;
    private javax.swing.JComboBox<String> quaCadTurma;
    private javax.swing.JComboBox<String> quaTurma;
    private javax.swing.JComboBox<String> quinCadTurma;
    private javax.swing.JComboBox<String> quinTurma;
    private javax.swing.JComboBox<String> segCadTurma;
    private javax.swing.JComboBox<String> segTurma;
    private javax.swing.JComboBox<String> sexCadTurma;
    private javax.swing.JComboBox<String> sexTurma;
    private javax.swing.JComboBox<String> terCadTurma;
    private javax.swing.JComboBox<String> terTurma;
    // End of variables declaration//GEN-END:variables
}
