/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Instrutor.InstAluno;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import objetos.Exercicio;
import objetos_dao.ExercicioDAO;

/**
 *
 * @author Marco Antônio
 */
public class EditAlunoExerc extends javax.swing.JFrame {

    /**
     * Creates new form EditAlunoExerc
     */
    Exercicio antigo, novo;
    OpAlunoExerc opae;
    
    public EditAlunoExerc(Exercicio antigo, Exercicio novo, OpAlunoExerc opae) {
        this.antigo = antigo;
        this.novo = novo;
        this.opae = opae;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConfirmaEditAlun = new javax.swing.JButton();
        nomeEditAlun1 = new javax.swing.JLabel();
        NutrEditAlun2 = new javax.swing.JLabel();
        nomeEditAlun2 = new javax.swing.JLabel();
        NomeEditAlun2 = new javax.swing.JLabel();
        exercicioEdit2 = new javax.swing.JLabel();
        CancelaEditAlun = new javax.swing.JButton();
        SexoEditAlun1 = new javax.swing.JLabel();
        CPFEditAlun1 = new javax.swing.JLabel();
        SetaEditAlun = new javax.swing.JLabel();
        equipEdit1 = new javax.swing.JLabel();
        NutrEditAlun1 = new javax.swing.JLabel();
        Titulo1 = new javax.swing.JLabel();
        equipEdit2 = new javax.swing.JLabel();
        exercicioEdit1 = new javax.swing.JLabel();
        repEdit2 = new javax.swing.JLabel();
        NomeEditAlun1 = new javax.swing.JLabel();
        SexoEditAlun2 = new javax.swing.JLabel();
        repEdit1 = new javax.swing.JLabel();
        CPFEditAlun2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        ConfirmaEditAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ConfirmaEditAlun.setText("Sim");
        ConfirmaEditAlun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmaEditAlunActionPerformed(evt);
            }
        });

        nomeEditAlun1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeEditAlun1.setText("???");

        NutrEditAlun2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NutrEditAlun2.setText("Equipamento:");
        NutrEditAlun2.setToolTipText("");

        nomeEditAlun2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeEditAlun2.setText("???");

        NomeEditAlun2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeEditAlun2.setText("Aluno:");
        NomeEditAlun2.setToolTipText("");

        exercicioEdit2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        exercicioEdit2.setText("???");

        CancelaEditAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CancelaEditAlun.setText("Cancelar");
        CancelaEditAlun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelaEditAlunActionPerformed(evt);
            }
        });

        SexoEditAlun1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        SexoEditAlun1.setText("Repetições:");
        SexoEditAlun1.setToolTipText("");

        CPFEditAlun1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CPFEditAlun1.setText("Exercício:");
        CPFEditAlun1.setToolTipText("");

        SetaEditAlun.setFont(new java.awt.Font("Dialog", 1, 55)); // NOI18N
        SetaEditAlun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SetaEditAlun.setText("→");

        equipEdit1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        equipEdit1.setText("???");

        NutrEditAlun1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NutrEditAlun1.setText("Equipamento:");
        NutrEditAlun1.setToolTipText("");

        Titulo1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo1.setText("Editar o exercício: ");
        Titulo1.setToolTipText("");

        equipEdit2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        equipEdit2.setText("???");

        exercicioEdit1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        exercicioEdit1.setText("???");

        repEdit2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        repEdit2.setText("???");

        NomeEditAlun1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeEditAlun1.setText("Aluno:");
        NomeEditAlun1.setToolTipText("");

        SexoEditAlun2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        SexoEditAlun2.setText("Repetições::");
        SexoEditAlun2.setToolTipText("");

        repEdit1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        repEdit1.setText("???");

        CPFEditAlun2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CPFEditAlun2.setText("Exercício:");
        CPFEditAlun2.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ConfirmaEditAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(CancelaEditAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(NomeEditAlun1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeEditAlun1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(CPFEditAlun1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(SexoEditAlun1)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(exercicioEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(repEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NutrEditAlun1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(equipEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(10, 10, 10)
                                .addComponent(SetaEditAlun)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SexoEditAlun2)
                            .addComponent(CPFEditAlun2)
                            .addComponent(NutrEditAlun2)
                            .addComponent(NomeEditAlun2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exercicioEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equipEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeEditAlun2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Titulo1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomeEditAlun1)
                            .addComponent(nomeEditAlun1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CPFEditAlun1)
                                    .addComponent(exercicioEdit1))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SexoEditAlun1)
                                    .addComponent(repEdit1))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(equipEdit1)
                                    .addComponent(NutrEditAlun1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(SetaEditAlun))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomeEditAlun2)
                            .addComponent(nomeEditAlun2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CPFEditAlun2)
                            .addComponent(exercicioEdit2))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SexoEditAlun2)
                            .addComponent(repEdit2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NutrEditAlun2)
                            .addComponent(equipEdit2))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConfirmaEditAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelaEditAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmaEditAlunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmaEditAlunActionPerformed

        try {
            new ExercicioDAO().altera(antigo, novo);            
            opae.Limpar();
            throw new Exception("Exercicio alterado com sucesso");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            dispose();
        }
    }//GEN-LAST:event_ConfirmaEditAlunActionPerformed

    private void CancelaEditAlunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelaEditAlunActionPerformed
        dispose();
    }//GEN-LAST:event_CancelaEditAlunActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        nomeEditAlun1.setText(antigo.getAluno().getNome());
        exercicioEdit1.setText(antigo.getNome());
        repEdit1.setText(String.valueOf(antigo.getRepeticao()));
        equipEdit1.setText(antigo.getEquipamento().getNome());
        
        nomeEditAlun2.setText(novo.getAluno().getNome());
        exercicioEdit2.setText(novo.getNome());
        repEdit2.setText(String.valueOf(novo.getRepeticao()));
        equipEdit2.setText(novo.getEquipamento().getNome()); 
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPFEditAlun1;
    private javax.swing.JLabel CPFEditAlun2;
    private javax.swing.JButton CancelaEditAlun;
    private javax.swing.JButton ConfirmaEditAlun;
    private javax.swing.JLabel NomeEditAlun1;
    private javax.swing.JLabel NomeEditAlun2;
    private javax.swing.JLabel NutrEditAlun1;
    private javax.swing.JLabel NutrEditAlun2;
    private javax.swing.JLabel SetaEditAlun;
    private javax.swing.JLabel SexoEditAlun1;
    private javax.swing.JLabel SexoEditAlun2;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel equipEdit1;
    private javax.swing.JLabel equipEdit2;
    private javax.swing.JLabel exercicioEdit1;
    private javax.swing.JLabel exercicioEdit2;
    private javax.swing.JLabel nomeEditAlun1;
    private javax.swing.JLabel nomeEditAlun2;
    private javax.swing.JLabel repEdit1;
    private javax.swing.JLabel repEdit2;
    // End of variables declaration//GEN-END:variables
}
