/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Instrutor.InstAluno;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import objetos.Exercicio;
import objetos_dao.ExercicioDAO;

/**
 *
 * @author Marco Antônio
 */
public class ExcAlunoExerc extends javax.swing.JFrame {

    Exercicio exercicio;
    OpAlunoExerc opae;
    
    public ExcAlunoExerc(Exercicio exercicio, OpAlunoExerc opae) {
        this.exercicio = exercicio;
        this.opae = opae;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeEditAlun1 = new javax.swing.JLabel();
        nomeEditAlun1 = new javax.swing.JLabel();
        CPFEditAlun1 = new javax.swing.JLabel();
        exercicioEdit1 = new javax.swing.JLabel();
        SexoEditAlun1 = new javax.swing.JLabel();
        repEdit1 = new javax.swing.JLabel();
        NutrEditAlun1 = new javax.swing.JLabel();
        equipEdit1 = new javax.swing.JLabel();
        ConfirmaEditAlun = new javax.swing.JButton();
        CancelaEditAlun = new javax.swing.JButton();
        Titulo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(376, 270));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        NomeEditAlun1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeEditAlun1.setText("Aluno:");
        NomeEditAlun1.setToolTipText("");

        nomeEditAlun1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeEditAlun1.setText("???");

        CPFEditAlun1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CPFEditAlun1.setText("Exercício:");
        CPFEditAlun1.setToolTipText("");

        exercicioEdit1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        exercicioEdit1.setText("???");

        SexoEditAlun1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        SexoEditAlun1.setText("Repetições:");
        SexoEditAlun1.setToolTipText("");

        repEdit1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        repEdit1.setText("???");

        NutrEditAlun1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NutrEditAlun1.setText("Equipamento:");
        NutrEditAlun1.setToolTipText("");

        equipEdit1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        equipEdit1.setText("???");

        ConfirmaEditAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ConfirmaEditAlun.setText("Sim");
        ConfirmaEditAlun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmaEditAlunActionPerformed(evt);
            }
        });

        CancelaEditAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CancelaEditAlun.setText("Cancelar");
        CancelaEditAlun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelaEditAlunActionPerformed(evt);
            }
        });

        Titulo1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo1.setText("Excluir o exercício:");
        Titulo1.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addComponent(NomeEditAlun1)
                                    .addGap(18, 18, 18)
                                    .addComponent(nomeEditAlun1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(SexoEditAlun1)
                                        .addComponent(NutrEditAlun1)
                                        .addComponent(CPFEditAlun1))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(equipEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(repEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(exercicioEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addComponent(Titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(203, 203, 203)
                            .addComponent(CancelaEditAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(ConfirmaEditAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeEditAlun1)
                    .addComponent(nomeEditAlun1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exercicioEdit1)
                    .addComponent(CPFEditAlun1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SexoEditAlun1)
                    .addComponent(repEdit1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equipEdit1)
                    .addComponent(NutrEditAlun1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmaEditAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelaEditAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmaEditAlunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmaEditAlunActionPerformed

        try {
            new ExercicioDAO().remove(exercicio);
            opae.Limpar();
            throw new Exception("Exercício excluído com sucesso");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            dispose();
        }
    }//GEN-LAST:event_ConfirmaEditAlunActionPerformed

    private void CancelaEditAlunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelaEditAlunActionPerformed
        dispose();
    }//GEN-LAST:event_CancelaEditAlunActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        nomeEditAlun1.setText(exercicio.getAluno().getNome());
        exercicioEdit1.setText(exercicio.getNome());
        repEdit1.setText(String.valueOf(exercicio.getRepeticao()));
        equipEdit1.setText(exercicio.getEquipamento().getNome());
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPFEditAlun1;
    private javax.swing.JButton CancelaEditAlun;
    private javax.swing.JButton ConfirmaEditAlun;
    private javax.swing.JLabel NomeEditAlun1;
    private javax.swing.JLabel NutrEditAlun1;
    private javax.swing.JLabel SexoEditAlun1;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel equipEdit1;
    private javax.swing.JLabel exercicioEdit1;
    private javax.swing.JLabel nomeEditAlun1;
    private javax.swing.JLabel repEdit1;
    // End of variables declaration//GEN-END:variables
}
