/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Administrador.AdmEquipamentos;

import Objetos_DAO.EquipamentoDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import objetos.Equipamento;

/**
 *
 * @author gabri
 */
public class EditEquipAlerta extends javax.swing.JFrame {

    EquipamentoDAO EquipamentoBanco = new EquipamentoDAO();
    Equipamento Equipamento_novo;
    Equipamento Equipamento_antigo;
   
   OpEquipamentos ope;
   
    public EditEquipAlerta(Equipamento Equipamento_antigo, Equipamento Equipamento_novo, OpEquipamentos ope) {
        
        this.Equipamento_antigo = Equipamento_antigo;
        this.Equipamento_novo = Equipamento_novo;
        this.ope = ope;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeExcEquip = new javax.swing.JLabel();
        nomeEditEquip1 = new javax.swing.JLabel();
        ConfirmaExcEquip = new javax.swing.JButton();
        CancelaExcEquip = new javax.swing.JButton();
        MarcaExcEquip = new javax.swing.JLabel();
        marcaExcEquip = new javax.swing.JLabel();
        FabricanteExcEquip = new javax.swing.JLabel();
        statusEditEquip1 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        SetaEditFunc = new javax.swing.JLabel();
        FabricanteExcEquip1 = new javax.swing.JLabel();
        statusEditEquip2 = new javax.swing.JLabel();
        NomeExcEquip1 = new javax.swing.JLabel();
        nomeEditEquip2 = new javax.swing.JLabel();
        ManuCadEquip = new javax.swing.JLabel();
        uEditEquip1 = new com.toedter.calendar.JDateChooser();
        ManuCadEquip1 = new javax.swing.JLabel();
        pEditEquip1 = new com.toedter.calendar.JDateChooser();
        ManuCadEquip2 = new javax.swing.JLabel();
        pEditEquip2 = new com.toedter.calendar.JDateChooser();
        ManuCadEquip3 = new javax.swing.JLabel();
        uEditEquip2 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        NomeExcEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeExcEquip.setText("Nome:");
        NomeExcEquip.setToolTipText("");

        nomeEditEquip1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeEditEquip1.setText("???");

        ConfirmaExcEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ConfirmaExcEquip.setText("Sim");
        ConfirmaExcEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmaExcEquipActionPerformed(evt);
            }
        });

        CancelaExcEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CancelaExcEquip.setText("Cancelar");
        CancelaExcEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelaExcEquipActionPerformed(evt);
            }
        });

        MarcaExcEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        MarcaExcEquip.setToolTipText("");

        marcaExcEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        FabricanteExcEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        FabricanteExcEquip.setText("Staus:");
        FabricanteExcEquip.setToolTipText("");

        statusEditEquip1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        statusEditEquip1.setText("???");

        Titulo.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Editar Equipamento:");
        Titulo.setToolTipText("");

        SetaEditFunc.setFont(new java.awt.Font("Dialog", 1, 55)); // NOI18N
        SetaEditFunc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SetaEditFunc.setText("→");

        FabricanteExcEquip1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        FabricanteExcEquip1.setText("Staus:");
        FabricanteExcEquip1.setToolTipText("");

        statusEditEquip2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        statusEditEquip2.setText("???");

        NomeExcEquip1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeExcEquip1.setText("Nome:");
        NomeExcEquip1.setToolTipText("");

        nomeEditEquip2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeEditEquip2.setText("???");

        ManuCadEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ManuCadEquip.setText("Ultima Manutenção:");

        uEditEquip1.setEnabled(false);
        uEditEquip1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        ManuCadEquip1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ManuCadEquip1.setText("Proxima Manutenção:");

        pEditEquip1.setEnabled(false);
        pEditEquip1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        ManuCadEquip2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ManuCadEquip2.setText("Proxima Manutenção:");

        pEditEquip2.setEnabled(false);
        pEditEquip2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        ManuCadEquip3.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ManuCadEquip3.setText("Ultima Manutenção:");

        uEditEquip2.setEnabled(false);
        uEditEquip2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(NomeExcEquip)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(nomeEditEquip1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(FabricanteExcEquip)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(statusEditEquip1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(ManuCadEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(MarcaExcEquip, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(SetaEditFunc)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(marcaExcEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(NomeExcEquip1)
                                        .addGap(18, 18, 18)
                                        .addComponent(nomeEditEquip2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(FabricanteExcEquip1)
                                        .addGap(18, 18, 18)
                                        .addComponent(statusEditEquip2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uEditEquip1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ManuCadEquip3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ManuCadEquip2)
                                    .addComponent(uEditEquip2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pEditEquip1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(120, 120, 120)
                                .addComponent(pEditEquip2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ManuCadEquip1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(ConfirmaExcEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(CancelaExcEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomeExcEquip)
                            .addComponent(nomeEditEquip1))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MarcaExcEquip)
                            .addComponent(marcaExcEquip)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomeExcEquip1)
                            .addComponent(nomeEditEquip2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FabricanteExcEquip1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusEditEquip2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(4, 4, 4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SetaEditFunc)
                            .addComponent(FabricanteExcEquip)
                            .addComponent(statusEditEquip1))))
                .addGap(18, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManuCadEquip)
                    .addComponent(ManuCadEquip3))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uEditEquip1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uEditEquip2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ManuCadEquip2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pEditEquip2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(ManuCadEquip1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pEditEquip1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConfirmaExcEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelaExcEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmaExcEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmaExcEquipActionPerformed
        try {
            // Click no Botão Sim:
            EquipamentoBanco.altera(Equipamento_novo);
            //System.out.println(Equipamento_novo.getNome());
            dispose();
            JOptionPane.showMessageDialog(null, "Equipamento Editado com Sucesso!!!");
            
            ope.Limpar();
        } catch (Exception ex) {
            Logger.getLogger(EditEquipAlerta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ConfirmaExcEquipActionPerformed
   
    private void CancelaExcEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelaExcEquipActionPerformed
        // Click no Botão Cancelar:

        dispose();
    }//GEN-LAST:event_CancelaExcEquipActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         // Quando Abre a Janela

        //Antes
        nomeEditEquip1.setText(Equipamento_antigo.getNome());
        statusEditEquip1.setText(Equipamento_antigo.getStatus());
        pEditEquip1.setDate(Equipamento_antigo.getP_manutencao());
        uEditEquip1.setDate(Equipamento_antigo.getU_manutencao());

        //Depois
        
        nomeEditEquip2.setText(Equipamento_novo.getNome());
        statusEditEquip2.setText(Equipamento_novo.getStatus());
        pEditEquip2.setDate(Equipamento_novo.getP_manutencao());
        uEditEquip2.setDate(Equipamento_novo.getU_manutencao());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelaExcEquip;
    private javax.swing.JButton ConfirmaExcEquip;
    private javax.swing.JLabel FabricanteExcEquip;
    private javax.swing.JLabel FabricanteExcEquip1;
    private javax.swing.JLabel ManuCadEquip;
    private javax.swing.JLabel ManuCadEquip1;
    private javax.swing.JLabel ManuCadEquip2;
    private javax.swing.JLabel ManuCadEquip3;
    private javax.swing.JLabel MarcaExcEquip;
    private javax.swing.JLabel NomeExcEquip;
    private javax.swing.JLabel NomeExcEquip1;
    private javax.swing.JLabel SetaEditFunc;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel marcaExcEquip;
    private javax.swing.JLabel nomeEditEquip1;
    private javax.swing.JLabel nomeEditEquip2;
    private com.toedter.calendar.JDateChooser pEditEquip1;
    private com.toedter.calendar.JDateChooser pEditEquip2;
    private javax.swing.JLabel statusEditEquip1;
    private javax.swing.JLabel statusEditEquip2;
    private com.toedter.calendar.JDateChooser uEditEquip1;
    private com.toedter.calendar.JDateChooser uEditEquip2;
    // End of variables declaration//GEN-END:variables
}
