/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Administrador.AdmEquipamentos;

import Objetos_DAO.EquipamentoDAO;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetos.Equipamento;

/**
 *
 * @author Marco Antônio
 */
public class OpEquipamentos extends javax.swing.JPanel {

    /**
     * Creates new form Temp
     */
    
    EquipamentoDAO EquipamentoBanco = new EquipamentoDAO();
    public static Equipamento tempEquip = new Equipamento();
    public static int indice = -1;
    
    public OpEquipamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        TelaEquip = new javax.swing.JTabbedPane();
        AbaEquip = new javax.swing.JPanel();
        NomeEquip = new javax.swing.JLabel();
        nomeEquip = new javax.swing.JLabel();
        IDEquip = new javax.swing.JLabel();
        idEquip = new javax.swing.JLabel();
        ManuEquip = new javax.swing.JLabel();
        uManuEquip = new javax.swing.JLabel();
        StatusEquip = new javax.swing.JLabel();
        statusEquip = new javax.swing.JLabel();
        ManuEquip1 = new javax.swing.JLabel();
        pManuEquip = new javax.swing.JLabel();
        AbaCadEquip = new javax.swing.JPanel();
        NomeCadEquip = new javax.swing.JLabel();
        nomeCadEquip = new javax.swing.JTextField();
        ManuCadEquip = new javax.swing.JLabel();
        manuCadEquip = new com.toedter.calendar.JDateChooser();
        StatusCadEquip = new javax.swing.JLabel();
        statusCadEquip = new javax.swing.JComboBox<>();
        EditarEquip = new javax.swing.JButton();
        ExcluirEquip = new javax.swing.JButton();
        ManuCadEquip1 = new javax.swing.JLabel();
        manuCadEquip_p = new com.toedter.calendar.JDateChooser();
        CadastrarEquip = new javax.swing.JButton();
        TabelaPesquisaEquip = new javax.swing.JPanel();
        ScrollTabelaEquip = new javax.swing.JScrollPane();
        TabelaEquip = new javax.swing.JTable();
        Limpar = new javax.swing.JButton();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        Titulo.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Equipamentos");

        TelaEquip.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        AbaEquip.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NomeEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeEquip.setText("Nome:");

        nomeEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        IDEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        IDEquip.setText("ID:");

        idEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        ManuEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ManuEquip.setText("Ultima Manutenção:");

        uManuEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        StatusEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        StatusEquip.setText("Status:");

        statusEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        ManuEquip1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ManuEquip1.setText("Próxima Manutenção:");

        pManuEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout AbaEquipLayout = new javax.swing.GroupLayout(AbaEquip);
        AbaEquip.setLayout(AbaEquipLayout);
        AbaEquipLayout.setHorizontalGroup(
            AbaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaEquipLayout.createSequentialGroup()
                .addGroup(AbaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaEquipLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IDEquip)
                        .addGap(18, 18, 18)
                        .addComponent(idEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154)
                        .addComponent(ManuEquip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uManuEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AbaEquipLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(AbaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaEquipLayout.createSequentialGroup()
                                .addComponent(NomeEquip)
                                .addGap(18, 18, 18)
                                .addComponent(nomeEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ManuEquip1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pManuEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AbaEquipLayout.createSequentialGroup()
                                .addComponent(StatusEquip)
                                .addGap(18, 18, 18)
                                .addComponent(statusEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        AbaEquipLayout.setVerticalGroup(
            AbaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaEquipLayout.createSequentialGroup()
                .addGroup(AbaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaEquipLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(AbaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ManuEquip)
                            .addComponent(uManuEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaEquipLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AbaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDEquip)
                            .addComponent(idEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(AbaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeEquip)
                    .addComponent(nomeEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManuEquip1)
                    .addComponent(pManuEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AbaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusEquip)
                    .addComponent(statusEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        TelaEquip.addTab("Equipamentos", AbaEquip);

        AbaCadEquip.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NomeCadEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NomeCadEquip.setText("Nome:");

        nomeCadEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeCadEquip.setPreferredSize(new java.awt.Dimension(74, 32));

        ManuCadEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ManuCadEquip.setText("Ultima Manutenção:");

        manuCadEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        StatusCadEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        StatusCadEquip.setText("Status:");

        statusCadEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        statusCadEquip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponivel", "Indisponivel" }));
        statusCadEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusCadEquipActionPerformed(evt);
            }
        });

        EditarEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        EditarEquip.setText("Editar");
        EditarEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarEquipActionPerformed(evt);
            }
        });

        ExcluirEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ExcluirEquip.setText("Excluir");
        ExcluirEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirEquipActionPerformed(evt);
            }
        });

        ManuCadEquip1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ManuCadEquip1.setText("Proxima Manutenção:");

        manuCadEquip_p.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        manuCadEquip_p.setMinSelectableDate(new java.util.Date());

        CadastrarEquip.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CadastrarEquip.setText("Cadastrar");
        CadastrarEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarEquipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AbaCadEquipLayout = new javax.swing.GroupLayout(AbaCadEquip);
        AbaCadEquip.setLayout(AbaCadEquipLayout);
        AbaCadEquipLayout.setHorizontalGroup(
            AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCadEquipLayout.createSequentialGroup()
                .addGroup(AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AbaCadEquipLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(AbaCadEquipLayout.createSequentialGroup()
                                .addComponent(StatusCadEquip)
                                .addGap(18, 18, 18)
                                .addComponent(statusCadEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(ManuCadEquip1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(manuCadEquip_p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(AbaCadEquipLayout.createSequentialGroup()
                                .addComponent(NomeCadEquip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeCadEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ManuCadEquip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(manuCadEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AbaCadEquipLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(CadastrarEquip)
                        .addGap(31, 31, 31)
                        .addComponent(EditarEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(ExcluirEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        AbaCadEquipLayout.setVerticalGroup(
            AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCadEquipLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ManuCadEquip)
                        .addComponent(nomeCadEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NomeCadEquip))
                    .addComponent(manuCadEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(StatusCadEquip)
                        .addComponent(statusCadEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ManuCadEquip1))
                    .addComponent(manuCadEquip_p, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(AbaCadEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditarEquip)
                    .addComponent(ExcluirEquip)
                    .addComponent(CadastrarEquip))
                .addGap(16, 16, 16))
        );

        TelaEquip.addTab("Controle", AbaCadEquip);

        TabelaPesquisaEquip.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TabelaEquip.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabelaEquip.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TabelaEquip.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "ID", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaEquip.setToolTipText("");
        TabelaEquip.setAlignmentX(1.0F);
        TabelaEquip.setAlignmentY(1.0F);
        TabelaEquip.setRowHeight(28);
        TabelaEquip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaEquipMouseClicked(evt);
            }
        });
        ScrollTabelaEquip.setViewportView(TabelaEquip);

        Limpar.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TabelaPesquisaEquipLayout = new javax.swing.GroupLayout(TabelaPesquisaEquip);
        TabelaPesquisaEquip.setLayout(TabelaPesquisaEquipLayout);
        TabelaPesquisaEquipLayout.setHorizontalGroup(
            TabelaPesquisaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelaPesquisaEquipLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Limpar)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabelaPesquisaEquipLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ScrollTabelaEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TabelaPesquisaEquipLayout.setVerticalGroup(
            TabelaPesquisaEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelaPesquisaEquipLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(Limpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollTabelaEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TelaEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TabelaPesquisaEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TelaEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TabelaPesquisaEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void statusCadEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusCadEquipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusCadEquipActionPerformed

    private void EditarEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarEquipActionPerformed
        // Botão Editar Funcionario

        try {
            //if (indice >= 0 && !idCadEquip.getText().isEmpty()) {

                if( nomeCadEquip.getText().isBlank() ||
                    statusCadEquip.getSelectedItem() == null ||
                    manuCadEquip.getDate() == null ||
                    manuCadEquip_p.getDate() == null)
                throw new Exception();

                tempEquip = new Equipamento();

                tempEquip.setId((int)TabelaEquip.getValueAt(indice, 1));
                tempEquip.setNome(nomeCadEquip.getText());
                tempEquip.setU_manutencao(new Date( manuCadEquip.getDate().getTime()));
                tempEquip.setP_manutencao(new Date (manuCadEquip_p.getDate().getTime()));
                tempEquip.setStatus(statusCadEquip.getSelectedItem().toString());

                EditEquipAlerta EEA = new EditEquipAlerta(EquipamentoBanco.getLista().get(indice), tempEquip, this);
                EEA.setVisible(true);

                //}
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Selecione o Equipamento na Tabela e Preencha Todos os Campos Corretamente!!!");
            indice = -1;
        }
    }//GEN-LAST:event_EditarEquipActionPerformed

    private void CadastrarEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarEquipActionPerformed

        try {

            if( nomeCadEquip.getText().isBlank() ||
                statusCadEquip.getSelectedItem() == null ||
                manuCadEquip.getDate() == null ||
                manuCadEquip_p.getDate() == null){
                throw new Exception();
            }

            boolean i = true;
            tempEquip= new Equipamento();
            tempEquip.setNome(nomeCadEquip.getText());
            //tempEquip.setId(Integer.valueOf( idCadEquip.getText()));

            if(statusCadEquip.getSelectedItem().equals("Disponivel")){
                tempEquip.setStatus("Disponivel");}
            else{
                tempEquip.setStatus("Indisponivel");}

            tempEquip.setU_manutencao(new Date(manuCadEquip.getDate().getTime()));
            tempEquip.setP_manutencao(new Date(manuCadEquip_p.getDate().getTime()));

            //tempEquip.setImagem(iconToByte(new ImageIcon(iconToImage(fotoCadAlun.getIcon()))));

            ArrayList<Equipamento> equipamentos = EquipamentoBanco.getLista();

            //for (Equipamento a : equipamentos) {

                //if ( Integer.valueOf(a.getId()).equals(Integer.valueOf(idCadEquip.getText()))) {
                    //JOptionPane.showMessageDialog(null, "Equipamento já Existente!!!");
                    //i = false;
                    //}
                //}

            if (i || equipamentos.isEmpty()) {
                //System.out.println(tempEquip.toString());
                EquipamentoBanco.adiciona(tempEquip);

                JOptionPane.showMessageDialog(null, "Equipamento Cadastrado com Sucesso!");
                Limpar();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_CadastrarEquipActionPerformed

    private void TabelaEquipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaEquipMouseClicked

        try {                                         
            
            indice = TabelaEquip.getSelectedRow();
            Equipamento equipamento=  EquipamentoBanco.getEquipamento((int) TabelaEquip.getValueAt(indice, 1));
            
            SimpleDateFormat date = new SimpleDateFormat("dd/MM/yyyy ");
            
            try {
                if (indice >= 0 && equipamento != null) {
                    
                    //Funcionário
                    nomeEquip.setText(equipamento.getNome());
                    statusEquip.setText(equipamento.getStatus());
                    idEquip.setText(Integer.toString(equipamento.getId()));
                    pManuEquip.setText(date.format(equipamento.getP_manutencao()));                    
                    uManuEquip.setText(date.format(equipamento.getU_manutencao()));
                    
                    //Controle
                    nomeCadEquip.setText(equipamento.getNome());
                    
                    switch(equipamento.getStatus()){
                        
                        case "Disponivel":
                            statusCadEquip.setSelectedItem("Disponivel");
                            break;
                            
                        case "Indisponivel":
                            statusCadEquip.setSelectedItem("Indisponivel");
                            break;
                            
                    }
                    
                    manuCadEquip.setDate(equipamento.getU_manutencao());
                    manuCadEquip_p.setDate(equipamento.getP_manutencao());
                    nomeCadEquip.setEditable(true);
                    statusCadEquip.setEnabled(true);
                    
                    CadastrarEquip.setEnabled(false);
                    EditarEquip.setEnabled(true);
                    ExcluirEquip.setEnabled(true);
                    
                } else {
                    
                    JOptionPane.showMessageDialog(null, "Selecione o equipamento na tabela");
                    indice = -1;
                }
                
            } catch (NumberFormatException | IndexOutOfBoundsException e) {
                
                JOptionPane.showMessageDialog(null, "Selecione um equipamento válido");
                indice = -1;
            }
            
        } catch (Exception ex) {

            Logger.getLogger(OpEquipamentos.class.getName()).log(Level.SEVERE,null, ex);
        }

    }//GEN-LAST:event_TabelaEquipMouseClicked

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        Limpar();
    }//GEN-LAST:event_LimparActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        CadastrarEquip.setEnabled(true);
        EditarEquip.setEnabled(false);
        ExcluirEquip.setEnabled(false);
        
        AtualizaTabela();
    }//GEN-LAST:event_formAncestorAdded

    private void ExcluirEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirEquipActionPerformed
         try {

            if (indice >= 0) {

                ExcEquipAlerta EEA = new ExcEquipAlerta(EquipamentoBanco.getLista().get(indice), this);
                EEA.setVisible(true);

                Limpar();
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Selecione um equipamento válido na tabela");
            indice = -1;
        }
    }//GEN-LAST:event_ExcluirEquipActionPerformed
    public void Limpar(){
        CadastrarEquip.setEnabled(true);
        EditarEquip.setEnabled(false);
        ExcluirEquip.setEnabled(false);
        
        nomeCadEquip.setText("");
        manuCadEquip.setDate(null);
        manuCadEquip_p.setDate(null);
        
        idEquip.setText("");
        nomeEquip.setText("");
        StatusEquip.setText("");
        uManuEquip.setText("");
        pManuEquip.setText("");
        
        AtualizaTabela();
    }
    
     public void AtualizaTabela() {

        try {
            DefaultTableModel TF = (DefaultTableModel) TabelaEquip.getModel();
            TF.setNumRows(0);
            
            ArrayList<Equipamento> Equipamentos = EquipamentoBanco.getLista();
            
            for (int i = 0; i <Equipamentos.size(); i++) {
                
                TF.addRow(new Object[]{
                    Equipamentos.get(i).getNome(),
                    Equipamentos.get(i).getId(),
                    Equipamentos.get(i).getStatus(),
                    
                });
            }
        } catch (Exception ex) {
            Logger.getLogger(OpEquipamentos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AbaCadEquip;
    private javax.swing.JPanel AbaEquip;
    private javax.swing.JButton CadastrarEquip;
    private javax.swing.JButton EditarEquip;
    private javax.swing.JButton ExcluirEquip;
    private javax.swing.JLabel IDEquip;
    private javax.swing.JButton Limpar;
    private javax.swing.JLabel ManuCadEquip;
    private javax.swing.JLabel ManuCadEquip1;
    private javax.swing.JLabel ManuEquip;
    private javax.swing.JLabel ManuEquip1;
    private javax.swing.JLabel NomeCadEquip;
    private javax.swing.JLabel NomeEquip;
    private javax.swing.JScrollPane ScrollTabelaEquip;
    private javax.swing.JLabel StatusCadEquip;
    private javax.swing.JLabel StatusEquip;
    private javax.swing.JTable TabelaEquip;
    private javax.swing.JPanel TabelaPesquisaEquip;
    private javax.swing.JTabbedPane TelaEquip;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel idEquip;
    private com.toedter.calendar.JDateChooser manuCadEquip;
    private com.toedter.calendar.JDateChooser manuCadEquip_p;
    private javax.swing.JTextField nomeCadEquip;
    private javax.swing.JLabel nomeEquip;
    private javax.swing.JLabel pManuEquip;
    private javax.swing.JComboBox<String> statusCadEquip;
    private javax.swing.JLabel statusEquip;
    private javax.swing.JLabel uManuEquip;
    // End of variables declaration//GEN-END:variables
}
