/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Administrador.AdmPagamentos;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import objetos.Pagamento;
import objetos_dao.PagamentoDAO;

/**
 *
 * @author Marco Antônio
 */
public class ExcPagamentoAlerta extends javax.swing.JFrame {

    Pagamento pagamento;
    OpPagamentos op;
    
    public ExcPagamentoAlerta(Pagamento pagamento, OpPagamentos op) {
        this.pagamento = pagamento;
        this.op = op;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeAluno = new javax.swing.JLabel();
        dataPagamento = new javax.swing.JLabel();
        valorPagamento = new javax.swing.JLabel();
        ConfirmaEditAlun = new javax.swing.JButton();
        CancelaEditAlun = new javax.swing.JButton();
        Titulo1 = new javax.swing.JLabel();
        TelefoneCadAlun1 = new javax.swing.JLabel();
        TelefoneCadAlun2 = new javax.swing.JLabel();
        TelefoneCadAlun3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        nomeAluno.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeAluno.setText("???");

        dataPagamento.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        dataPagamento.setText("???");

        valorPagamento.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        valorPagamento.setText("???");

        ConfirmaEditAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ConfirmaEditAlun.setText("Sim");
        ConfirmaEditAlun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmaEditAlunActionPerformed(evt);
            }
        });

        CancelaEditAlun.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CancelaEditAlun.setText("Cancelar");
        CancelaEditAlun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelaEditAlunActionPerformed(evt);
            }
        });

        Titulo1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo1.setText("Excluir o pagamento:");
        Titulo1.setToolTipText("");

        TelefoneCadAlun1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        TelefoneCadAlun1.setText("Aluno:");

        TelefoneCadAlun2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        TelefoneCadAlun2.setText("Data:");

        TelefoneCadAlun3.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        TelefoneCadAlun3.setText("Valor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TelefoneCadAlun1)
                                .addComponent(TelefoneCadAlun2)
                                .addComponent(TelefoneCadAlun3))
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valorPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(Titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(203, 203, 203)
                            .addComponent(CancelaEditAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(ConfirmaEditAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeAluno)
                    .addComponent(TelefoneCadAlun1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(valorPagamento))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TelefoneCadAlun2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataPagamento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TelefoneCadAlun3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmaEditAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelaEditAlun, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmaEditAlunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmaEditAlunActionPerformed

        try {
            
            new PagamentoDAO().remove(pagamento);
            op.AtualizaTabelaPagamento();
            throw new Exception("Pagamento excluído com sucesso");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            dispose();
        }
    }//GEN-LAST:event_ConfirmaEditAlunActionPerformed

    private void CancelaEditAlunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelaEditAlunActionPerformed
        dispose();
    }//GEN-LAST:event_CancelaEditAlunActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        nomeAluno.setText(pagamento.getAluno().getNome());
        dataPagamento.setText(new SimpleDateFormat("dd/MM/yyyy").format(pagamento.getData()));
        valorPagamento.setText("R$"+String.format("%.2f", pagamento.getValor()));
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelaEditAlun;
    private javax.swing.JButton ConfirmaEditAlun;
    private javax.swing.JLabel TelefoneCadAlun1;
    private javax.swing.JLabel TelefoneCadAlun2;
    private javax.swing.JLabel TelefoneCadAlun3;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel dataPagamento;
    private javax.swing.JLabel nomeAluno;
    private javax.swing.JLabel valorPagamento;
    // End of variables declaration//GEN-END:variables
}
